### ISSUE TITLE
Asking for missing config values returns the previously found value

### ISSUE THREAD

**Issue by MarkBorcherding** [DannyBen/bashly#107]
We probably either need to add `local` all over the place in  the lib function or clear all the values you tend to use.  

Example of how to make it behave unexpectedly: 

```sh
config_init

echo First we try get foo \"$(config_get foo)\" and it is not there
echo so we set it to BOOM
config_set foo BOOM
echo now it is is \"$(config_get foo)\" which is great
echo but now every missing thing is \"$(config_get baz)\" which is not so great
```

**Comment by DannyBen** [comment]
Thanks. Actually the bug is simple, and for now you can fix it in your `src/lib/config.sh`

Inside the `config_get()` function, just add `local value=""`, so it starts like this:

```bash
config_get() {
  key=$1
  regex="^$key *= *(.+)$"
  local value=""  # <= this was added
  #...
```

I will fix it soon, thanks for the report.

**Comment by DannyBen** [comment]
This is now fixed in master. If you want you can use the master version, or you can just take the updated [config lib file](https://github.com/DannyBen/bashly/blob/master/lib/bashly/templates/lib/config.sh).

Let me know if you still see any issue, otherwise, I will release it in the next few days.

**Comment by MarkBorcherding** [comment]
Yup. I've already done that too. Using `local` has the side  benefit of scoping that to _just_ that function. I was _also_ using `key` and `value` in our command's function....and was stepping on this value.

Thanks for being so responsive.
