### ISSUE TITLE
Feature request: allow sub-commands to be hidden from help text

### ISSUE THREAD

**Issue by JakobGM** [DannyBen/bashly#149]
Hi, @DannyBen! :wave: 

We are happy users of Bashly at @kolonialno, having written much of our internal data science tooling with it, thanks a lot! :bow: Let me start by explaining what I want to _achieve_ in order to prevent us having an [XY Problem](https://xyproblem.info/) on our hands.

## Problem to be solved

We are starting to amass a lot of sub-commands in on of our internal CLIs, and would like to clean up the help text and logic a bit. For instance, one of our commands `cli_name sub_command <arg>` is in practice just some glorified switch logic which invokes either `cli_name sub_command_arg1`, `cli_name sub_command_arg2`, or `cli_name sub_command_arg3` based on the value of `<arg>`. In fact, we intend our internal users to never invoke `cli_name sub_command_arg{1,2,3}` directly, and only invoke it through `cli_name sub_command`. We could in theory move the logic of the sub-commands into library functions, but then we lose all the nice tooling provided by Bashly for those commands; argument parsing and validation, and dependency checking come to mind.

## Proposed solution

If bashly provided an additional optional key in the `command` object configuration, let's say `hidden: true`, which excludes the given sub-command from the output of `cli_name` and `cli_name --help`, but still allows the command to be directly executed with `cli_name sub_command` and documentation with `cli_name sub_command --help`.

Another use-case for this parameter would be to release sub-commands in "Beta mode", hidden from most users, but you can do a soft launch by letting a subset of the CLI users know that the new sub-command is available on direct invocation.

## Alternative solution

Another solution that comes to mind is something more along the lines of "library functions" only for commands instead. Perhaps a command could be annotated as a "library command" or "private command", making it exclusively available in the namespace of the command implementations, but not outside from the perspective of the CLI user.

Thanks in advance,
Jakob

**Comment by DannyBen** [comment]
Hi Jakob,

It is nice to hear that you make extensive use of bashly, I hope it is useful and pleasant for the most part.

As for the problem at hand, I feel that it might take a more real-world example to illustrate the problem. Bashly tries to keep things simple, and attempt to drive you towards making good decisions. On that note, if something is not a command open to the users, it should not be defined as such.

So, trying to understand your issue by my own interpretation, imagine cli that needs to respond to `cli connect (ssh|https|telnet)` - which is similar to your use case, as I see it.

In this case, you can use the `allowed` directive, to limit the allowed values for the `protocol` arg, like so:

```yaml
name: cli

commands:
- name: connect
  help: Connect to the metaverse

  args:
  - name: protocol
    required: true
    allowed: [ssh, https, telnet]
    help: Protocol to use for connection
```

Furthermore, I hope you are familiar with the `bashly add lib` command, and the fact that you can add any code inside the `src/lib` folder, and it will be included as well.

This functionality allows you to define the following code in your `connect_command.sh`:

```bash
protocol=${args[protocol]}
connect_$protocol
```

and it will call a subsequent function based on the provided `protocol` arg.

Of course, this is only one way of solving the issue.

That said, adding an ability to hide something from the usage text is probably not that big of a problem, I am just not convinced yet it is needed. 

If you can share a more realistic version of the problem (while still keeping it concise), it might help.

**Comment by wolfgang42** [comment]
I've been thinking of filing this feature request myself, so here's my 2¢ on an example of this problem:

The `git` command has “porcelain” subcommands (like `clone`, `switch`, `diff`, etc) that are intended for ordinary use, and “plumbing” subcommands (like `rev-parse`, `commit-tree`, or `interpret-trailers`) which need to be exposed so they can be used for scripting and unusual uses, but are not relevant to the ordinary course of things. This latter category are still “full” subcommands (both in the sense that they have flags and need argument parsing etc, and also in that they should be available to call from outside the script), but do not need to appear in ordinary help output, and can be relegated to external documentation. I've been putting them in a separate group to get them out of the way of the main help output, but being able to hide them altogether would be nice.

(It sounds like @JakobGM intends for these commands to *not* be used by external programs, but in the spirit of keeping things simple is OK with just documenting such rather than adding options to Bashly to enforce it.)

**Comment by DannyBen** [comment]
Thanks @wolfgang42, this is an interesting use case. I can see the value.
In fact, I have already implemented something that I believe solves it:

Setting any command to `private: true` will just avoid showing it in the Commands list.
It will still be available when running `cli hiddencommand --help`.

As it seems, this feature crossed the minds of at least two users - I figure there is no harm in adding it. If any of you wish to validate the PR I am about to attach to this ticket in a few minutes, it will be great and we can release it quickly.
