### ISSUE TITLE
Unhelpful error "undefined method `size' for nil:NilClass" with invalid bashly.yml

### ISSUE THREAD

**Issue by wolfgang42** [DannyBen/bashly#156]
This YAML (note the misspelled key):
```yaml
name: example
commands:
  - mane: test # [sic]
```

produces the following output:
```
creating user files in src
skipped src/initialize.sh (exists)
skipped src/_command.sh (exists)
NoMethodError
undefined method `size' for nil:NilClass
```

and also creates an extraneous file called `src/_command.sh`. 

It took me a while to figure out where things had gone wrong, seems like there is should be some added validations somewhere to catch the case of an invalid command object?

**Comment by DannyBen** [comment]
Yes. I encountered this error while working on the YAML import.

I wonder if it is time for a proper validation before processing. Perhaps a standard schema validation?

**Comment by DannyBen** [comment]
After examining these schema validators, I came to the conclusion that they are too heavy duty for bashly. Each of bashly's configuration structures (command, argument etc) are already Ruby objects. It should be easy to add a simple `#valid?` method to them, that will just check the absolute must (e.g. that a command has a `name`, and a flag has a `short`).
