### ISSUE TITLE
Heredoc and function indentation

### ISSUE THREAD

**Issue by dacrystal** [DannyBen/bashly#163]
Currently is not possible to use `heredoc` in command due to space indentation. It results in syntax error:
 ```sh
warning: here-document at line ?? delimited by end-of-file (wanted "EOF")
```

In order to support `heredoc`, it must be used it with `<<-` (NB `-` suffix). And `bashly` must replace **space** indentation with **tab** in `:command.function`, ` :command.initialize` and `:command.root_command` or just replace all **spaces** indentation with **tabs** for consistency.

Command with `heredoc`:
```sh
# cat root_command.sh
cat <<- EOF
Testing heredoc
EOF
```

Successfully tested with:
```diff
diff --git a/lib/bashly/extensions/array.rb b/lib/bashly/extensions/array.rb
index d32548f..a73e812 100644
--- a/lib/bashly/extensions/array.rb
+++ b/lib/bashly/extensions/array.rb
@@ -1,7 +1,7 @@
 class Array
-  def indent(offset)
+  def indent(offset, indent_string = " ")
     return self unless offset > 0
-    indentation = " " * offset
+    indentation = indent_string * offset
     map { |line| "#{indentation}#{line}" }
   end
 end
diff --git a/lib/bashly/extensions/string.rb b/lib/bashly/extensions/string.rb
index 2faf0e4..fbe4657 100644
--- a/lib/bashly/extensions/string.rb
+++ b/lib/bashly/extensions/string.rb
@@ -3,9 +3,9 @@ class String
     gsub("\n", "\\n").gsub("\"", "\\\"")
   end
 
-  def indent(offset)
+  def indent(offset, indent_string = " ")
     return self unless offset > 0
-    split("\n").indent(offset).join("\n")
+    split("\n").indent(offset, indent_string).join("\n")
   end
 
   def to_underscore
diff --git a/lib/bashly/views/command/function.erb b/lib/bashly/views/command/function.erb
index 7b34862..75a3b75 100644
--- a/lib/bashly/views/command/function.erb
+++ b/lib/bashly/views/command/function.erb
@@ -1,4 +1,4 @@
 # :command.function
 <%= function_name %>_command() {
-<%= load_user_file(filename).indent 2 %>
+<%= load_user_file(filename).indent(1, "\t") %>
 }
diff --git a/lib/bashly/views/command/initialize.erb b/lib/bashly/views/command/initialize.erb
index f1a7cc6..41ae597 100644
--- a/lib/bashly/views/command/initialize.erb
+++ b/lib/bashly/views/command/initialize.erb
@@ -4,5 +4,5 @@ initialize() {
   long_usage=''
   <%= ENV['BASHLY_STRICT'] ? "set -euo pipefail" : "set -e" %>
 
-<%= load_user_file("initialize.sh", placeholder: false).indent 2 %>
+<%= load_user_file("initialize.sh", placeholder: false).indent(1, "\t") %>
 }
diff --git a/lib/bashly/views/command/root_command.erb b/lib/bashly/views/command/root_command.erb
index b77835d..124cea0 100644
--- a/lib/bashly/views/command/root_command.erb
+++ b/lib/bashly/views/command/root_command.erb
@@ -1,4 +1,4 @@
 # :command.root_command
 root_command() {
-<%= load_user_file("root_command.sh").indent 2 %>
+<%= load_user_file("root_command.sh").indent(1, "\t") %>
 }
```

**Comment by DannyBen** [comment]
There is a lot of indentation done by bashly, and I am not sure how I feel about replacing spaces with tabs just for heredoc support. As far as I can tell, tab character as indentation is discouraged in practically all languages.

See #73 for a duplicate issue and a possible workaround.

Thanks for the implementation suggestion though - I might come back to it if new evidence come to light as to the importance of having support for heredoc.

**Comment by dacrystal** [comment]
My bad maybe I misspelled "heredoc" when I searched issue history.

I'll have a look at the workaround.

Anyway, I'm not a fan of tabs either but just this use case.

**Comment by DannyBen** [comment]
> Anyway, I'm not a fan of tabs either but just this use case.

I understand. 
I found out that I am not a fan of heredoc - seems like an archaic approach to creating long strings. Rarely use them anywhere. Combine the dislike for tabs and for heredocs, and I feel there are usually better ways to handle the problem that heredoc comes to solve.

**Comment by DannyBen** [comment]
cc @dacrystal 

Bashly 0.7.10 was released, with improved support for cases where heredoc is needed.

By settings the `BASHLY_TAB_INDENT=1` environment variable (or via the new [settings.yml](https://bashly.dannyb.co/usage/settings/)), the generated script will have all its leading spaces indented as tabs instead, which allows use of this heredoc format:

```bash
cat <<-EOF
multiline
heredoc text
EOF
```

See the [heredoc example](https://github.com/DannyBen/bashly/tree/master/examples/heredoc#readme).

**Comment by DannyBen** [comment]
I have made heredoc work naturally, without the need to do anything (#496). bashly will no longer apply additional indentation to the strings inside a heredoc block.

This is available in the edge version, if anyone wishes to test it.
