### ISSUE TITLE
Wrong permissions on gen files using docker

### ISSUE THREAD

**Issue by insign** [DannyBen/bashly#165]
When I run commands using docker run, the generated files comes with root permissions.
I made an alias to fast fix this but I believe that there a fix using just docker.

```shell
bashly() {
    docker run --rm -it --volume "$PWD:/app" dannyben/bashly
    sudo chown -R $USER src
}
```

**Comment by DannyBen** [comment]
This is how docker works. 
The docker wrapper around Bashly is provided for convenience. If you can use the Ruby gem installation, it is better.

**Comment by DannyBen** [comment]
I found something that can help.

Add `--user $(id -u):$(id -g)`

For example: 

```
docker run --rm -it --user $(id -u):$(id -g) -v $PWD:/app dannyben/bashly init
```

You can of course use this as the alias.
If this works for you, I will update the instructions.

**Comment by insign** [comment]
It fixed the issue, but not sure why but the alias give me error, so here the alias which work:
```shell
alias bashly='docker run --rm -it --user $(id -u):$(id -g) -v $PWD:/app dannyben/bashly "$@"'
```
The error when not using `"$@"`:

```
creating user files in src
Errno::ENOENT
No such file or directory @ rb_sysopen - src/bashly.yml
```

**Comment by DannyBen** [comment]
Which shell and OS are you using?

**Comment by insign** [comment]
> Which shell and OS are you using?

zsh, it works fine without $@ in bash

**Comment by DannyBen** [comment]
> zsh, it works fine without $@ in bash

Interesting. So zsh aliases behave differently than bash.
I will update the docs. Not sure if I should post the zsh version or the common version, but this can be updated at any time.

Thanks for the report.

**Comment by DannyBen** [comment]
I will close this - feel free to comment if you think we should continue the discussion.

**Comment by insign** [comment]
BTW, in zsh, completions doesn't work for flags. In bash, works fine. Since it is primarily targeted to bash, I am not sure if it is a bug or if an issue is needed.

**Comment by DannyBen** [comment]
Converted to issue, lets discuss there.
