### ISSUE TITLE
Allow alternate names for "lib" folder

### ISSUE THREAD

**Issue by nsainaney** [DannyBen/bashly#184]
First off, thanks for a great tool!

We have a sizable monorepo and all our packages build into lib folders so we have lib in our .gitignores and our cleanup scripts. When running the cleanup scripts, our bashly libs get deleted. It's not a huge deal and we've augmented our gitignore with:

```
packages/**/lib
!packages/**/src/lib
```

and our del scripts with:

```
del **/lib !**/src/lib !**/node_modules/**/lib
```

but if we could choose an alternate name, it'll be a nice-to-have.

Thanks again

**Comment by DannyBen** [comment]
Happy to hear bashly is used in larger contexts.

Allowing configuration of the `lib` folder is a great idea, and I believe quite easy to implement.
I will work on it tomorrow.

**Comment by DannyBen** [comment]
This was implemented and will be released with the next version.
