### ISSUE TITLE
Here documents not working due to indentation

### ISSUE THREAD

**Issue by tianyuanhao** [DannyBen/bashly#210]
```sh
··# src/hello_command.sh
··cat << EOF
··hello
··EOF
```

**Comment by DannyBen** [comment]
Can't be helped. Heredocs are a messy language construct that rely on improper indentation.

See #73 and #163

**Comment by DannyBen** [comment]
I have added an example of the only way to use heredoc in bashly.
https://github.com/DannyBen/bashly/tree/master/examples/heredoc#readme

**Comment by DannyBen** [comment]
cc @tianyuanhao 

Bashly 0.7.10 was released, with improved support for cases where heredoc is needed.

By settings the `BASHLY_TAB_INDENT=1` environment variable (or via the new [settings.yml](https://bashly.dannyb.co/usage/settings/)), the generated script will have all its leading spaces indented as tabs instead, which allows use of this heredoc format:

```bash
cat <<-EOF
multiline
heredoc text
EOF
```

See the [heredoc example](https://github.com/DannyBen/bashly/tree/master/examples/heredoc#readme).

**Comment by DannyBen** [comment]
I have made heredoc work naturally, without the need to do anything (#496). bashly will no longer apply additional indentation to the strings inside a heredoc block.

This is available in the edge version, if anyone wishes to test it.
