### ISSUE TITLE
Improve autocomplete for flag arguments

### ISSUE THREAD

**Issue by tiagoposse** [DannyBen/bashly#224]
Could autocompletions be made so that when trying to autocomplete a flag, only allowed values for it are shown?

As an example, given the following command:
```
commands:
- name: deploy

  args:
  - name: name
    required: true
    help: Name of the service
    repeatable: true
    allowed: [ a, b, c ]
  flags:
  - long: --stage
    short: -s
    help: Stage to manage
    arg: stage
    allowed:
      - dev
      - test
      - prod
```

Autocompletions will be as follows:
```
./cli deploy <TAB>
--help          a            test
--stage        b           prod
-h                 c
-s                 dev
```

Triggering autocomplete for the `-s` flag will result in the same autocompletions being shown:
```
./cli deploy -s <TAB>
--help          a            test
--stage        b           prod
-h                 c
-s                 dev
```

Would be clearer if:
- when autocompleting a command, show possible flags and allowed values for the positional argument
- when autocompleting a flag, show possible values for the flag only

Example:
For the command:
```
./cli deploy <TAB>
--help          a
--stage        b
-h                 c
-s
```

For the flag
```
./cli deploy -s <TAB>
dev
test
prod
```

**Comment by DannyBen** [comment]
The short answer is no.

Completions are provided by the [completely gem](https://github.com/DannyBen/completely).
What you are describing requires a more elaborate completions script that looks back at any given time, and makes a different decision as to the suggested completions. 

The only way I could come up with to automatically generate a completions script, was to:

1. Look for the longest possible **fixed** part of the typed command
2. Present all the **non fixed** arguments and flags as a list of possible completions.

You can easily see what I mean by running this in your bashly folder:

```
$ bashly add comp yaml
$ bashly add comp script
```

The YAML will be:

```yaml
cli:
- "--help"
- "--version"
- "-h"
- "-v"
- deploy
cli deploy:
- "--help"
- "--stage"
- "-h"
- "-s"
- a
- b
- c
- dev
- prod
- test
```

and the script will be (partial):

```bash
  case "$comp_line" in
    'deploy'*) COMPREPLY=($(compgen -W "--help --stage -h -s a b c dev prod test" -- "$cur")) ;;
    ''*) COMPREPLY=($(compgen -W "--help --version -h -v deploy" -- "$cur")) ;;
  esac
```

If you have a way of converting a simple data structure (YAML) to a more elaborate lookback-based completions script, we can discuss this (preferably in the completely gem repo), but I suspect the complexity of such a script is not going to be worth it.

If you look at completions script for complex tools (like git), you will see they are extremely long and complex. This cannot be generated automatically I suspect, and if it can, it will not be easy.

**Comment by tiagoposse** [comment]
I see what you mean.

This is what I had imagined, considering how the completely yaml looks like:
```
cli:
- "--help"
- "--version"
- "-h"
- "-v"
- deploy
cli deploy*-s):
- "--help"
- "-h"
- dev
- prod
- test
cli deploy*--stage:
- "--help"
- "-h"
- dev
- prod
- test
cli deploy:
- "--help"
- "--stage"
- "-h"
- "-s"
- a
- b
- c
```

So that the completion script is generated like:
```
  case "$comp_line" in
    deploy*-s) COMPREPLY=($(compgen -W "--help -h dev prod test" -- "$cur")) ;;
    deploy*--stage) COMPREPLY=($(compgen -W "--help -h dev prod test" -- "$cur")) ;;
    deploy) COMPREPLY=($(compgen -W "--help --stage -h -s a b c" -- "$cur")) ;;
    ''*) COMPREPLY=($(compgen -W "--help --version -h -v deploy" -- "$cur")) ;;
  esac
```

This seems to adhere to the current schema of the completely gem, but I might be wrong here.
Additionally, this still won't allow the complex use-case of dynamic flag autocompletion.

**Comment by tiagoposse** [comment]
Awesome! Thanks for the support and happy to help where I can

**Comment by DannyBen** [comment]
This manually crafted script works as you expect I think. Can you confirm?

```bash
#!/usr/bin/env bash

# This bash completions script was generated by
# completely (https://github.com/dannyben/completely)
# Modifying it manually is not recommended
_cli_completions() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local comp_line="${COMP_WORDS[@]:1}"

  case "$comp_line" in
    'deploy'*'--stage'*) COMPREPLY=($(compgen -W "dev prod test" -- "$cur")) ;;
    'deploy'*'-s'*) COMPREPLY=($(compgen -W "dev prod test" -- "$cur")) ;;
    'deploy'*) COMPREPLY=($(compgen -W "--help --stage -h -s a b c" -- "$cur")) ;;
    ''*) COMPREPLY=($(compgen -W "--help --version -h -v deploy" -- "$cur")) ;;
  esac
}

complete -F _cli_completions cli
```

If so - I feel it is doable to implement, but will require changes both in completely and bashly - so before that, lets just confirm that it provides a good example (and hopefully also confirm that it supports more complex / realistic use cases)

**Comment by tiagoposse** [comment]
I can confirm this works:
```
_cli_completions() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local comp_line="${COMP_WORDS[@]:1}"

  case "$comp_line" in
    deploy*--stage) COMPREPLY=($(compgen -W "dev prod test" -- "$cur")) ;;
    deploy*-s) COMPREPLY=($(compgen -W "dev prod test" -- "$cur")) ;;
    deploy*) ; COMPREPLY=($(compgen -W "--help --stage -h -s a b c" -- "$cur")) ;;
    *) COMPREPLY=($(compgen -W "--help --version -h -v deploy" -- "$cur")) ;;
  esac
}
```

No quote games necessary.
It's important that flag completion lines do not end with *, in order to enforce completion just for the flag: `deploy*-s` in my example instead of `deploy*-s*` in yours.

Examples:
```
cli deploy <TAB>
--help   --stage  -h       -s       a        b        c
```

```
cli deploy -s <TAB>
dev test prod
```

```
cli deploy -s dev <TAB>
--help   --stage  -h       -s       a        b        c
```

In case it matters:
```
bash --version
GNU bash, version 5.1.16
```

**Comment by DannyBen** [comment]
So far I found a couple of issues with this approach. The main issue is that the asterisk at the end is important - without it, partial completions are not triggered:

```
# this works
$ script --stage <TAB>
dev test prod

# this does not
$ script --stage pr<TAB>
```

since the `$compline` will not match anything, and will go to the final wildcard match.

**Comment by tiagoposse** [comment]
You most likely had the quotes because of spaces in the patterns:
`commandA subcommandB )` does not work, but `commandA' 'subcommandB matches.

Did some more testing today and came up with the following:
```
_cli_completions() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local comp_line="${COMP_WORDS[@]:1}"

  case "$comp_line" in
    prev[[:space:]]deploy*--stage?([[:space:]]*([^[:space:]])) ) COMPREPLY=($(compgen -W "dev devev test" -- "$cur")) ;;
    deploy*-s?([[:space:]]*([^[:space:]])) ) COMPREPLY=($(compgen -W "dev prod test" -- "$cur")) ;;
    deploy*) ; COMPREPLY=($(compgen -W "--help --stage -h -s a b c" -- "$cur")) ;;
    *) COMPREPLY=($(compgen -W "--help --version -h -v deploy" -- "$cur")) ;;
  esac
}
```

the "magic" would be to append `?([[:space:]]*([^[:space:]]))` after a flag, to provide partial matches the first word only, if at all provided.
The first pattern here is just to show how to get around the quoting issues.

**Comment by DannyBen** [comment]
No, this type of pattern matching is not an option. It is hard to read even in its simplest form, and I get syntax errors.

I think there are two options:

1. Set the `compline` variable to NOT include the values in `cur`
2. Switch from case and shell matching to if-else and regex matching

Also remember that all these use cases are expected to work:

Assuming the command is `cli command subcommand --protocol ssh`

- `cli <tab>`
- `cli com<tab>`
- `cli command <tab>`
- `cli command sub<tab>`
- `cli command subcommand <tab>`
- `cli command subcommand --pro<tab>`
- `cli command subcommand --protocol <tab>`
- `cli command subcommand --protocol s<tab>`

**Comment by tiagoposse** [comment]
> No, this type of pattern matching is not an option. It is hard to read even in its simplest form, and I get syntax errors.

I do agree this would be extremely hard to read. But it's weird that you're getting syntax errors, as all proposed completion scenarios work correctly in my environment.

I did consider proposing if/else regex matching, as this would be my go-to, but I can imagine this is more work.

**Comment by DannyBen** [comment]
So - in order to streamline our collaboration on this, I propose this file as the test file:

```bash
# comp.sh
_mycomps() {
  local cur compline
  _init_completion -s || return
  cur=${COMP_WORDS[COMP_CWORD]}
  compline="${COMP_WORDS[@]:1}"

  if [[ -n "$COMPLETELY_DEBUG" ]]; then
    echo "compline: '$compline'" > 'completely-debug.txt'
    echo "cur:      '$cur'" >> 'completely-debug.txt'
  fi

  case "$compline" in
    'command subcommand'*) COMPREPLY=($(compgen -W "--protocol ssh scp" -- "$cur")) ;;
    'command'*) COMPREPLY=($(compgen -W "subcommand" -- "$cur")) ;;
    *) COMPREPLY=($(compgen -W "--help command" -- "$cur")) ;;
  esac
} &&
complete -F _mycomps cli

# TESTS
source /usr/share/bash-completion/bash_completion

# usage: check NUMBER COMMAND EXPECTED
# where NUMBER is the number of words in the command, and substract one if the
# last word is partial that needs to be completed
check() {
  COMP_CWORD=$1
  COMP_WORDS=($2)
  expected="$3"
  _mycomps
  actual="${COMPREPLY[@]}"
  echo "compline: [${COMP_WORDS[*]}]"
  echo "expected: [$expected]"
  echo "actual:   [$actual]"
  [[ "$expected" == "$actual" ]] || echo "ERROR"
  echo
}

check 1 "cli" "--help command"
check 1 "cli comm" "command"
check 2 "cli command" "subcommand"
check 3 "cli command sub" "subcommand"
check 3 "cli command subcommand" "--protocol ssh scp"
check 3 "cli command subcommand --" "--protocol"
```

It includes the completion script + a testing facility + built in test cases.

Running this on my Ubuntu succeeds, and running it on a clean Docker ubuntu succeeds as well.

Since we have different systems, I also suggest that if you see it succeeds on your machine, test that it also works in a clean Ubuntu. Here is how to do it (assuming you have docker and docker-compose).

```dockerfile
# Dockerfile
FROM ubuntu
WORKDIR /app
RUN apt-get update && apt-get install bash-completion
```

```yaml
# docker-compose.yml
services:
  test:
    build: .
    image: bash-completions-test
    volumes:
      - .:/app
    command: bash -c /app/comp.sh
```

command to run:

```
$ docker compose run --rm test
```

**Comment by DannyBen** [comment]
And - this implementation **includes argument support** by ensuring the compline we test against does not include the last (active) word.

```bash
_mycomps() {
  local cur compline
  _init_completion -s || return
  cur=${COMP_WORDS[COMP_CWORD]}
  compline="${COMP_WORDS[@]:1:$COMP_CWORD-1}"

  if [[ -n "$COMPLETELY_DEBUG" ]]; then
    echo "compline: '$compline'" > 'completely-debug.txt'
    echo "cur:      '$cur'" >> 'completely-debug.txt'
  fi

  case "$compline" in
    'command subcommand'*'--protocol') COMPREPLY=($(compgen -W "ssh scp" -- "$cur")) ;;
    'command subcommand') COMPREPLY=($(compgen -W "--protocol" -- "$cur")) ;;
    'command') COMPREPLY=($(compgen -W "subcommand" -- "$cur")) ;;
    *) COMPREPLY=($(compgen -W "--help command" -- "$cur")) ;;
  esac
} &&
complete -F _mycomps cli

# TESTS
source /usr/share/bash-completion/bash_completion

# usage: check NUMBER COMMAND EXPECTED
# where NUMBER is the number of words in the command, and substract one if the
# last word is partial that needs to be completed
check() {
  COMP_CWORD=$1
  COMP_WORDS=($2)
  expected="$3"
  _mycomps
  actual="${COMPREPLY[@]}"
  echo "compline: [${COMP_WORDS[*]}]"
  echo "expected: [$expected]"
  echo "actual:   [$actual]"
  [[ "$expected" == "$actual" ]] || echo "ERROR"
  echo
}

check 1 "cli" "--help command"
check 1 "cli comm" "command"
check 2 "cli command" "subcommand"
check 2 "cli command sub" "subcommand"
check 3 "cli command subcommand" "--protocol"
check 3 "cli command subcommand --" "--protocol"
check 4 "cli command subcommand --protocol" "ssh scp"
```

**Comment by DannyBen** [comment]
@tiagoposse - I believe most of the work from the "completely" side is done (except docs). The wildcard support is added and a tester command was added for easy testing (also of any other completion script, not generated by completely).

It would be great if you can test it. To do so, you need to use the github version of the gem by creating a Gemfile with the below contents in an empty directory:

```ruby
# Gemflile
source "https://rubygems.org"
gem 'completely', git: "https://github.com/dannyben/completely.git"
```

then run `bundle install` and then run everything with `bundle exec completely ...`

There is a sample `completely.yaml` with wildcard support [here](https://github.com/DannyBen/completely/blob/master/spec/fixtures/integration/gradual.yaml).

**Comment by DannyBen** [comment]
The new implementation is ready on the master branch. It was quite a lot of work, but I think the result is nice.

I will hold off on releasing it for a while, in case you are around to test it.

**Comment by tiagoposse** [comment]
Unfortunately I haven't had time to contribute as much as I wanted, but you've also been very fast, thanks for this!

I can confirm this works as expected for commands. However, aliases have the wrong behaviour:
```
services deploy <TAB>
--help          -h              a              c
--stage         -s              b
```

```
services deploy -s <TAB>
dev    prod      test
```

```
svc deploy <TAB>
d              deploy
b              build
```

```
svc deploy -s <TAB>
d              deploy
b              build
```

**Comment by DannyBen** [comment]
> However, aliases have the wrong behaviour:

Can you give me the smallest bashly or completely configuration to reproduce this?

**Comment by DannyBen** [comment]
I have tried with this simple bashly config (assuming you mean bashly command alias, and not bash `alias `command):

```yaml
name: cli
help: Sample application
version: 0.1.0

commands:
- name: services
  alias: svc
  help: Services list

  flags:
  - long: --protocol
    short: -p
    arg: NAME
    allowed: [ssh, scp, rsync]
    help: Help
```

Then, generated the `completely.yaml` with:

```
$ bashly add comp yaml completely.yaml -f
```

then tested it:

```
$ completely test "cli svc "
--help
--protocol
-h
-p

$ completely test "cli services "
--help
--protocol
-h
-p

$ completely test "cli svc --protocol "
ssh
scp
rsync
```

and all seems to be working as expected.

**Comment by tiagoposse** [comment]
this bashly.yml:
```
name: cli
help: Sample application
version: 0.1.0

commands:
- name: services
  alias: svc
  help: Services list

  commands:
    - name: deploy
      alias: [ d ]
      flags:
      - long: --protocol
        short: -p
        arg: NAME
        allowed: [ssh, scp, rsync]
        help: Help
```

Generates the following completely yaml:
```
root@29333cb80bcc:/work# bundle exec bashly add comp yaml completely.yaml -f
created completely.yaml

This file can be converted to a completions script using the completely gem.

root@29333cb80bcc:/work# cat completely.yaml
---
cli:
- "--help"
- "--version"
- "-h"
- "-v"
- services
- svc
cli services:
- "--help"
- "-h"
- d
- deploy
cli svc:
- "--help"
- "-h"
- d
- deploy
cli services deploy:
- "--help"
- "--protocol"
- "-h"
- "-p"
cli services deploy*--protocol: &1
- ssh
- scp
- rsync
cli services deploy*-p: *1
cli services d:
- "--help"
- "--protocol"
- "-h"
- "-p"
cli services d*--protocol: *1
cli services d*-p: *1
```

`cli services deploy` and `cli services d` exist in the list, `cli svc deploy` and `cli svc d` do not

**Comment by tiagoposse** [comment]
Additionally, the redesign seems to have introduced a dependency on bash-completion:
```
completely test "cli svc "
/tmp/completely-tester20220521-305-ucfj0o: line 61: /usr/share/bash-completion/bash_completion: No such file or directory
/tmp/completely-tester20220521-305-ucfj0o: line 10: _init_completion: command not found
```

**Comment by DannyBen** [comment]
> cli services deploy and cli services d exist in the list, cli svc deploy and cli svc d do not.

I see. This is a sub-sub command issue then. Need to take a look - this is a bashly issue at least, not a completely issue.

> Additionally, the redesign seems to have introduced a dependency on bash-completion:

True. This was introduced in https://github.com/DannyBen/completely/pull/12/files#diff-ac0f63cdec685cacfe02dcb7a4db85aa3b63dac0aae5dbbd3dca443d041b6b07.

The new completion template includes this `_init_completions` call, since pretty much every completion script in existence calls it. I am not even sure what it does for the purpose of our script, and if it is needed.

When running a script outside the scope of completions, the `_init_completions` function is not present, unless it is being sourced:

https://github.com/DannyBen/completely/blob/72d0da49076079c65acbbe64664c182398ebf14e/lib/completely/templates/tester-template.erb#L6

If you have any idea on how to untangle this, I am happy to hear.
So far, the only two options I see are:

1. Remove this `_init_competions` call, and then the sourcing of it.
2. Leave as is, and accept the dependency.

BTW - how come you do not have this file?

**Comment by tiagoposse** [comment]
> I see. This is a sub-sub command issue then. Need to take a look - this is a bashly issue at least, not a completely issue.

From the completely side everything looks like it's working perfectly.

> BTW - how come you do not have this file?

_init_completion is part of https://github.com/scop/bash-completion, which doesn't come pre-installed (at least in macos and ubuntu:
```
> docker run -ti --rm ubuntu
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
125a6e411906: Pull complete
Digest: sha256:26c68657ccce2cb0a31b330cb0be2b5e108d467f641c62e13ab40cbec258c68d
Status: Downloaded newer image for ubuntu:latest
root@33269dace814:/# _init_completion
bash: _init_completion: command not found

root@33269dace814:/# apt update && apt install -y bash-completion
Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
...
Unpacking bash-completion (1:2.11-5ubuntu1) ...
Setting up bash-completion (1:2.11-5ubuntu1) ...
root@33269dace814:/# source ~/.bashrc
root@33269dace814:/# . /usr/share/bash-completion/bash_completion
root@33269dace814:/# _init_completion
root@33269dace814:/#
```

Unfortunately I have no idea how to get around this.
Additionally, this dependency also broke support for zsh, but I guess this is not in scope for completely.

**Comment by DannyBen** [comment]
> Additionally, this dependency also broke support for zsh, but I guess this is not in scope for completely or bashly

Although I am not a zsh user, it is most definitely expected to work - especially if it used to and now it is broke.
I will open a separate issue in completely to track this. It needs to be fixed.

As for the fact that aliases of commands are not handled properly in completions - that is a **great** catch. I will open a new issue here to track this as well.

Thanks for the help so far - happy I waited for your input, it is invaluable.

**Comment by DannyBen** [comment]
@tiagoposse - do you know if you have the `_init_completion` function in zsh?
I wonder how come other bash completions work in zsh - since as I mentioned, they ALL call this function.

So what I am trying to figure out is this: Is it that the `_init_completion` function is missing in zsh, or is it just placed (sourced from) elsewhere.

**Comment by tiagoposse** [comment]
The function does not exist in zsh and is not used by zsh completions:
```
> grep -lir "_init_completion" ~/.oh-my-zsh/plugins/
> ls ~/.oh-my-zsh/plugins/ | wc -l
313
```

zsh has other (imo better and more complete) options for autocompletion.

> Thanks for the help so far - happy I waited for your input, it is invaluable.

Always happy to help, specially when it also solves a problem I have. Just a shame that I'm not familiar with ruby and I'm lacking time to get hands-on currently, otherwise I'd get to work myself.

**Comment by DannyBen** [comment]
Ok - I used the emergency brake and released a new completely version (0.4.1) without the breaking zsh changes.
Also the master branch of bashly requires completely 0.4.1 at least now.

If you can confirm that completions in zsh are no longer broken, it will be great.

In your folder where you have the Gemfile, you can run `bundle update` and you should get the latest branch and you can verify by running `completely --version` and expecting 0.4.1.

**Comment by tiagoposse** [comment]
confirmed it works both on zsh and bash 5.1 on macos with correct flag autocompletions 🎉 
On my end, this issue can be closed.

**Comment by DannyBen** [comment]
Excellent, thanks for confirming.

Will keep this issue open, but I believe we will continue discussion on #226 - which I hope to complete by tomorrow.

**Comment by DannyBen** [comment]
> echo "source <(cli install completions)" >> ~/.zshrc

And btw - there must be a better way for you to source your completions on startup. 
In bash there is a folder that is automatically sourced and is designed for completions - so you just put files there.
If you don't have such a facility in zsh, if I were you, I would create one (say ~/completions.d) and just add one function in your ~/.zshrc to load them all:

```bash
# Source all completions
for f in ~/completions.d/*; do source $f; done
```

**Comment by tiagoposse** [comment]
There's an easier way of loading via a file in a folder, I was just lazy when testing 😅

**Comment by DannyBen** [comment]
Version 0.8.1 is now released.

Note that the flag option now also supports providing custom completion (e.g. if you want to suggest branches for `--branch`) / [docs](https://bashly.dannyb.co/advanced/bash-completion/#custom-flag-completions), [example](https://github.com/DannyBen/bashly/tree/master/examples/completions#readme)

**Comment by DannyBen** [comment]
This was a nice one, thanks.
