### ISSUE TITLE
[FEATURE] JSON Library / JSON Parser

### ISSUE THREAD

**Issue by iocron** [DannyBen/bashly#239]
A YAML Parser exists as a library function, but is it possible to have a JSON Library / Parser as well (maybe something similar to the linux package [jq](https://stedolan.github.io/jq/))? 

This would open up a whole new range of functionality to developers, especially if someone needs to implement API based configuration. I have this challenge myself, if someone installs my CLI and if they don't have the user permissions to install linux packages, then they wont be able to use JSON at all.

**Comment by DannyBen** [comment]
Do you mean:

1. have a JSON bashly library that *uses* `jq`, or 
2. Implement JSON parsing in pure bash?

**Comment by DannyBen** [comment]
Not sure if you are still interested in the answer to your question, if so:

1. Writing a JSON parser in pure bash is outside the scope of bashly. If there is something like this already written, I can include it as a library in bashly.
2. Using `jq` is pretty much the go-to solution for JSON parsing in bash. It can be easily used in bashly, below is an example.

---

**Sample JSON file:**

```json
{
  "web": {
    "scale": 1,
    "ports": [
      "3000:3000",
      "80:4000"
    ]
  }    
}
```

**Sample bashly.yml file:**

```yaml
name: jsonsample
dependencies: [jq]

args:
- name: path
  required: true
  help: Path to JSON file
```

**The `src/root_command.sh` file:**

```bash
path="${args[path]}"

# Get a single value from the JSON
scale=$(jq -r .web.scale "$path")

# Get an array from the JSON
ports=( $(jq -r .web.ports[] "$path") )

echo "scale: $scale"
echo "ports:"
for port in ${ports[@]}; do
  echo "- $port"
done
```

I am going to close this, but can reopen if there is any interest.

**Comment by iocron** [comment]
Hello Ben, sry for my late reply. As you mentioned "Implement JSON parsing in pure bash?", yes, but I've dropped the idea, because this is too much of a hassle. I had the idea of making a dependency-free CLI API Library/Script based on Bash, but I quickly realized that there isn't a real alternative to jq, which is sad. I wished YAML and JSON would be already implemented by the OS natively in one or another way, it would make everything so much easier :D In fact, even jq has some serious parsing problems with some characters (e.g. a string combination with *). Sadly, that's how it is, maybe I can push some new ideas to the linux dev's :D Thank you for your time and consideration.

**Comment by DannyBen** [comment]
Sure thing. For JSON handline, you may also wish to check [`gron`](https://github.com/tomnomnom/gron) - its a nice little tool that flattens JSON, so it makes it really easy to grep and take one value from a given path. Just as an alternative to `jq`.
