### ISSUE TITLE
feature request: generate completions for fish an zsh

### ISSUE THREAD

**Issue by adrian-gierakowski** [DannyBen/bashly#242]
so the the cli's produced by bashly can be be used with ease in those shells

**Comment by DannyBen** [comment]
The completions generated by bashly (in fact by [completely](https://github.com/dannyben/completely)) should work in zsh, assuming you enabled bash completions in zsh. See [this StackOverflow answer](https://stackoverflow.com/questions/3249432/can-a-bash-tab-completion-script-be-used-in-zsh).

As for native completions for zsh or other shells, it is not really a priority for me, but I might look into it.
If you wish to help, then the work first be done in the completely gem.

**Comment by DannyBen** [comment]
I have looked into fish completions, it is outside the scope of what I feel like implementing.
In any case - if it will be implemented - it belongs in the completely gem, and not here.

zsh can support bash completions without a problem

I am closing this issue.
