### ISSUE TITLE
Presence of header.sh breaks executable

### ISSUE THREAD

**Issue by bkuhl** [DannyBen/bashly#246]
I'm running into an issue where when `src/header.sh` is present, I run into an error:

```
./my-cli: line 510: syntax error near unexpected token `<'
./my-cli: line 510: `  readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)'
```

I've confirmed I have the same problem running my CLI within `public.ecr.aws/docker/library/bash:5.1`.

I ran into this error early on when using bashly, but now that I've built our several commands I was revisiting it and it's reproduceable.  I should note that in this case, all that's in the `header.sh` file is:

```
# -----------------------------------------------------------------------------------
# This executable is generated from https://github.com/path-to/project
# -----------------------------------------------------------------------------------
```

Edit: Forgot to specify that this happens on both v0.8.2 and v0.8.3

**Comment by DannyBen** [comment]
I don't see how this can happen.

I need reproduction steps. When I try the most minimal reproduction, I see no issue.

1. `bashly init`
2. `bashly g`
3. Create `src/header.sh` with your content
4. `bashly g`
5. `./cli`
6. success

My guess is that you have something else in your script that breaks it.

**Comment by DannyBen** [comment]
Also: I am not sure if the header you posted is the **exact** header you are using. If so, it is not good. You need to add the bash shebang to it - could this be the culprit?

```bash
#!/usr/bin/env bash
# -----------------------------------------------------------------------------------
# This executable is generated from https://github.com/path-to/project
# -----------------------------------------------------------------------------------
```

**Comment by bkuhl** [comment]
🤦  How silly of me... it was the lack of the shebang.

**Comment by DannyBen** [comment]
Excellent. Solving problems without doing anything is my favorite kind of problem solving... :)

**Comment by DannyBen** [comment]
I have [reduced the chance of this happening again](https://bashly.dannyb.co/usage/writing-your-scripts/#custom-header) to someone else.
