### ISSUE TITLE
test/approve template missing

### ISSUE THREAD

**Issue by 780Farva** [DannyBen/bashly#251]
When trying to add tests to my project, I ran into an issue because a template wasn't installed when I installed bashly with bundle

![image](https://user-images.githubusercontent.com/16979385/190325963-ca75672b-36d6-4588-b9cf-e14d47e98ecc.png)

I'm using ubuntu 21.10, ruby v2.7.4, and bundler v2.2.5

Grabbing the raw file from github and creating the missing file seems to have resolved it for me, but I thought you might like to know that it was somehow missing on my system.

**Comment by DannyBen** [comment]
Absolutely! Thanks for reporting - I will look into it today.

**Comment by DannyBen** [comment]
Found the problem - the gem includes all the files that matche `*.*` - but since the `approve` file does not have an extension, it was not included in the bundle.

**Comment by DannyBen** [comment]
Fixed in 0.8.6
