### ISSUE TITLE
Send errors to stderr

### ISSUE THREAD

**Issue by taqtiqa-mark** [DannyBen/bashly#266]
>I never followed which output is sent to stdout and which to stderr.  If you feel there needs to be a change in how bashly outputs, and what are the exit codes - feel free to open a separate feature request.

_Originally posted by @DannyBen in https://github.com/DannyBen/bashly/issues/258#issuecomment-1261460035_

**Comment by DannyBen** [comment]
This issue needs details.

1. What is the expected behavior.
2. Why is it good.
3. Where can this behavior be observed in the wild.

**Comment by taqtiqa-mark** [comment]
> This issue needs details.
> 
>     1. What is the expected behavior.

When exiting in the error state send messages etc. `stderr`. Otherwise output goes to `stdout`.

>     2. Why is it good.

Logical.
POLS
Plays nice with monitoring and logging infra.

>     3. Where can this behavior be observed in the wild.

Docker 
Git

Implementation guidance/tips:
https://medium.com/@dirk.avery/the-bash-trap-trap-ce6083f36700

**Comment by taqtiqa-mark** [comment]
Also see utility functions in #267

**Comment by DannyBen** [comment]
So to make sure we are on the same page:

We want all the places that exit with non zero to print the error to stderr.

These are the places (all the snippets that `exit 1`):
https://github.com/DannyBen/bashly/search?q=exit+extension%3Agtx&type=code

**Comment by taqtiqa-mark** [comment]
I think so. If you're implementing trap handling.... it may help to offer users a function where they can place cleanup code - the corollary of `initialize.sh`: `terminate.sh`?

**Comment by DannyBen** [comment]
Not implementing any trap handling. The only change is that I `printf` to `>&2`.

**Comment by DannyBen** [comment]
This is now implemented in bashly 0.8.7
