### ISSUE TITLE
Issues with `normalize_input` and `catch_all`

### ISSUE THREAD

**Issue by surgiie** [DannyBen/bashly#274]
### Description

Not sure if this is a bug but maybe considered as one to some as it appears like this behavior is intentional and related to: https://github.com/DannyBen/bashly/issues/103

It seems that anytime `other_args` has `-` options in it, it gets split into multiple options, i.e `-foo` it ends up as `-f -o -o` 

A bit more as to why this is an issue:

I have a proxy command around `docker exec` that proxies a command  to a container, specifically to a mysql container that tries to run the  mysql cli with  `other_args` passed to it. 

When passing a password to `mysql` cli, it's attached to the `-p` flag, e.g `mysql -ppassword` 

When attempting to use `other_args` / `catch_all`, i.e `mycli mysql  -pexamplepassword`, im ending up with something like this:

`docker exec -it <my-container> mysql -u root -p -e -x -a -m -p -l -e -p -a -s -s -w -o -r -d `

Which in turn causes mysql to throw an error `mysql: [ERROR] mysql: unknown option '-e.`

Not sure what i can do to work around this as this appears to be an intended feature per the issue linked above?

**Comment by DannyBen** [comment]
Thanks for bringing that up.

The behavior you mention, is indeed intentional - however, it definitely should not interfere with `catch_all`.
Its a bug. I will take a look at it later.

**Comment by DannyBen** [comment]
One of the solutions I can think of to this problem, is to abort the operation of the `normalize_input` function when the commonly accepted separator `--` is observed.

So it will work like this:

```bash
$ ./cli -fd -- -foo --bar baz
# this file is located in 'src/root_command.sh'
# you can edit it freely and regenerate (it will not be overwritten)
args:
- ${args[--debug]} = 1
- ${args[--force]} = 1

other_args:
- ${other_args[*]} = -foo --bar baz
- ${other_args[0]} = -foo
- ${other_args[1]} = --bar
- ${other_args[2]} = baz
```

Is that an acceptable solution for your use case?

**Comment by surgiie** [comment]
Hrm I think so, but Im wondering about edge cases where you dont have this separator an curious if this is something that could be disabled via a setting? i feel like implicitly expanding options is a nice feature for some clis, it can be breaking for proxies to 3rd party clis like mysql. 🤔

**Comment by DannyBen** [comment]
> curious if this is something that could be disabled via a setting?

This is also a possibility. I think I can implement both the separator and the settings.

Keep in mind that the idea that `-abc` is equivalent to `-a -b -c` is - in my experience - the prevailing CLI behavior. All the CLIs that use "short flag notation" for long flags (`-debug` instead of `--debug`), use a less common syntax.

As bashly is opinionated, and these two approaches are mutually exclusive, I employed "my opinion" and implemented what I believe is the better standard.

I think I will add it as part of the [Settings](https://bashly.dannyb.co/usage/settings/#settings) feature, and *maybe* add the `--` separator as a "fallback".

Makes sense?

**Comment by DannyBen** [comment]
It will hopefully be mostly a matter of wrapping this:

https://github.com/DannyBen/bashly/blob/f9d6855eb904f0cbe676faf685ad162fdc47889d/lib/bashly/views/command/normalize_input.gtx#L14-L19

in `unless settings.disable_shortflag_expansion`

**Comment by surgiie** [comment]
that makes sense to me. 👍

**Comment by DannyBen** [comment]
I have implemented a new setting that can either be set in `settings.yml` (`compact_short_flags`) or an environment variable (`BASHLY_COMPACT_SHORT_FLAGS`).

Setting to false will not generate the piece of code that handles the compact flag notation.

If you wish to test it, it is in the master branch and in the docker `edge` image.

I want to first see if adding support for double dash is worthwhile.
Do you think this should be configurable as well? Or just add it as default for all?

**Comment by surgiie** [comment]
IMO configuration covers the most edge cases but opens up the door for bloating the source code if too much configuration is allowed. Ill leave it at your discretion if you want to make it the default.

**Comment by DannyBen** [comment]
Yes, I totally agree.

This `--` is giving me a shallow headache.... implementing it is easy, but then there is an artifact that makes this:

```
$ cli valid-arg invalid-arg -- a b c
```

place `a` `b` `c` and `invalid-arg` in the `other_args` array.
not sure it is acceptable.

**Comment by surgiie** [comment]
🤔 Yeah not sure.

I can confirm the new setting is working as expected using the `edge` docker image.

**Comment by DannyBen** [comment]
> I can confirm the new setting is working as expected using the `edge` docker image.

Excellent, thanks for confirming.
I will take a few more days to think about the double dash and release a new version on the weekend either with or without it.

**Comment by DannyBen** [comment]
@surgiie - it is my understanding that you personally do not need the double dash implementation, since you opted to disable flag compaction right?

If this is the case, I am currently leaning towards **not** implementing it, since it requires a surgical approach with more nuances than I anticipated.

**Comment by surgiie** [comment]
Correct. My original problem has been solves.

**Comment by DannyBen** [comment]
Thanks, I will close this issue for now. If there is demand from more users for double dash support, we will reconsider.
