### ISSUE TITLE
Ambiguous error messages

### ISSUE THREAD

**Issue by taqtiqa-mark** [DannyBen/bashly#277]
### Description
Ambiguous error messages
### Reproduction steps
``` 
$ bashly generate
TypeError
no implicit conversion of String into Integer
```
### Expected behavior

Identification of the error source

### Actual behavior
As above

**Comment by DannyBen** [comment]
That's a bug, I need the YAML that generated this error.

**Comment by taqtiqa-mark** [comment]
Trying to get a MRE, but it is more difficult with no debug or trace output.

**Comment by DannyBen** [comment]
You can get debug information by setting the `DEBUG` environment variable to anything before generating.

```
$ DEBUG=1 bashly g
```

https://github.com/DannyBen/bashly/blob/82913debccfc493d847e1f5fc962cae318c46e9f/bin/bashly#L13-L16

**Comment by taqtiqa-mark** [comment]
> My guess is that your YAML contains a an array instead of a hash somewhere, possibly indentation issues.

I believe that is correct.

**Comment by DannyBen** [comment]
Is there a YAML to reproduce this error?

**Comment by taqtiqa-mark** [comment]
Not yet. Somehow it was resolved. Happy to close as you wish.

**Comment by DannyBen** [comment]
Ok thanks.
I was trying to replicate it myself without luck - so I will close this.

If you encounter this again, we can revisit.
Thanks for reporting.
