### ISSUE TITLE
Make invalid `expose` warn instead of error

### ISSUE THREAD

**Issue by taqtiqa-mark** [DannyBen/bashly#278]
### Description
 
 Expose succeeds or warns

Currently, `expose: always`:

```bash
$ bashly generate
Bashly::ConfigurationError
root.commands[17].expose makes no sense without commands
```

**Comment by DannyBen** [comment]
Expose makes sense on a command that has no subcommands.
See [the docs](https://bashly.dannyb.co/configuration/command/#expose)

**Comment by taqtiqa-mark** [comment]
It shouldn't break a pipeline - is the idea - expose true with no subcommands is always harmless so why stop the world?

**Comment by DannyBen** [comment]
There are no warnings - if the file is invalid, it stops. If it is valid, it proceeds.

**Comment by taqtiqa-mark** [comment]
if the file is invalid there is no consequence: warning is sufficient

**Comment by DannyBen** [comment]
> if the file is invalid there is no consequence: warning is sufficient

No. The inner parts of bashly all assume a valid file. Any part of the file that should not be there, will error before proceeding.
I see no reason to change it, since when you see such an error it should be a very simple task for you to remove the offending section.

**Comment by taqtiqa-mark** [comment]
now we need two command templates + logic for no additional functionality, but just to stop bashly breaking our build?

**Comment by DannyBen** [comment]
> now we need two command templates + logic for no additional functionality, but just to stop bashly breaking our build?

Yes.

**Comment by DannyBen** [comment]
Are you using `import` to load multiple YAMLs?
If you can provide me with the most minimal use case (example YAMLs) that prevents you from creating a valid YAML file (without expose), I can perhaps think of ways to alleviate the issue.

For example - would it help if the loaded YAMLs support ERB, so you can write some minimal logic in them? Like:

```yaml
name: download
alias: d
help: Download a file
<%- if some_condition %>
expose: true
<%- end %>
```

One thing is certain - the requirement for a valid YAML is not going to change, but there may be other ways to make your use case easier.
