### ISSUE TITLE
Add support for loading lib files with different extensions

### ISSUE THREAD

**Issue by iamjackg** [DannyBen/bashly#307]
Hi Danny!
I was wondering if you'd be open to allowing for lib files with extensions other than `*.sh`.

My use case: I'm using shellcheck to validate my scripts, and I don't want to add a directive to each of the `.sh` files in `lib/` to tell it to treat it as bash (and I don't want to force it with a command line parameter either). I'd like to just rename all the files to `.bash` instead. 

This was easy enough to do with commands thanks to the `filename` directive, but there's no way around it for common functions.

**Comment by DannyBen** [comment]
Well, first of all, I am always open to suggestions.

But before we evaluate if we *can*, let's evaluate if we *should*.

Why aren't you running shellcheck only on the final script? This is what I do in all my bashly-generated scripts, and it is working great. I consider any use of the `filename` directive as a "code smell".

I recently also made the final scripts pass `shfmt` without complaing (except for [this issue](https://github.com/mvdan/sh/discussions/950) which I hope will be resolved soon on the shfmt side)

This way I am also running shellcheck in CI - [example 1](https://github.com/DannyBen/rush-repo/blob/master/.github/workflows/test.yml), [example 2](https://github.com/DannyBen/alf/blob/master/.github/workflows/test.yml)

**Comment by iamjackg** [comment]
A fair question! I'm certainly running shellcheck on the finished script as part of my pre-commit hooks and in CI, but my IDE also uses shellcheck to provide live feedback when working on individual files, which is useful and not something I'd want to give up.

**Comment by DannyBen** [comment]
Seems like this is more of a feature request for the developer of that shellcheck plugin or IDE integration.
`.sh` extension is often used for bash scripts, and not only for `sh` scripts. More than `.bash` is used. Doesn't is have a setting for it?

The `.sh` extension is quite rooted in bashly, in quite a few places. The built in libraries, with their auto upgrade for example is one area where it will probably be complicated to update so it can treat your use case fairly.

I wonder if this use case can be more easily bypassed.

**Comment by DannyBen** [comment]
And also - if you add a `#!/usr/bin/env bash` shebang at the top of the file (just as a temporary test) - does it treat it as bash?

**Comment by iamjackg** [comment]
It's actually default shellcheck behaviour: https://github.com/koalaman/shellcheck/pull/1464

And yep, the chain shellcheck uses is, in descending priority:
- command line flags (e.g. `--shell=bash`)
- shebang
- file extension

**Comment by iamjackg** [comment]
Note that I can solve this with my IDE plugin by simply telling it that, for this project, it should always pass `--shell=bash` to shellcheck. It's just a bit of a footgun if I ever need to add sh-compliant scripts to this project and forget I had set it, since it will also make it ignore the shebang altogether.

**Comment by DannyBen** [comment]
Well... although I feel that having bashly look at partials with `.bash` extension is the longest possible path to a solution, for what is presumably an edge case, I will take a look at the code.

Reading `.bash` is probably a two line change, but I am afraid of the quirks it might add for the more delicate mechanisms, such as library upgrades.

Also another suggestion for you to avoid the problem instead of solving it:
Don't place any other stuff in a bashly project. It is free to get more repositories in GitHub... :)

**Comment by iamjackg** [comment]
Yeah, all good points. I agree that it's definitely an edge case and, like you said, it might conflict with library upgrades. I don't have a good solution here.

The nuclear option would be to not enforce an extension at all: anything in `lib/` gets imported, period. This would obviously be a breaking change and potentially cause issues if people have readmes or other stuff in their lib folder.

**Comment by DannyBen** [comment]
> The nuclear option would be to not enforce an extension at all

Yeah, no. This is unlikely to happen. If anything, import `**/*.(sh,bash)`.
But this is the easy part. Libraries, auto generation of partial stubs (the initial `bashly generate`), checking if the file exists (what if there are both `.sh` and `.bash`) - and there are probably quite a few more issues.

This kind of decision - to be `.sh` extension on all - is a "foundation" for bashly. I never thought it will be challenged.
Nevertheless - I will examine the patient and try to find a way to accommodate.

**Comment by DannyBen** [comment]
BTW - since I see you care about the output of your scripts, get version 0.9.0 if you haven't.
It has improvements and a cleaner output ([changelog](https://github.com/DannyBen/bashly/blob/master/CHANGELOG.md#v090---2022-12-02)).

**Comment by DannyBen** [comment]
@iamjackg as it turns out, the code was pretty ready for accepting a user defined extension over the default `.sh`.

The path I have selected is using the settings facility.
If you are not familiar with it, you can either have a `settings.yml` in your root bashly dir (run `bashly add settings` to get the default one), or use environment variables.

More info here: https://bashly.dannyb.co/usage/settings/

The settings for the extension is called `partials_extension`.

The intention is to have only `sh` or `bash` throughout the bashly project directory.
I hope I covered all cases, specs have not been implemented yet.

**Comment by iamjackg** [comment]
Fantastic, thank you so much! I'm familiar with the settings, I think at this point I'm using pretty much every feature bashly offers :smile:

**Comment by DannyBen** [comment]
Heh. Cool.

I will merge then. Assuming you have a way to use the pre-release, I will postpone release until next weekend, to allow for additional features/fixes. Let me know if otherwise.

Thanks for bringing up those interesting cases.

**Comment by DannyBen** [comment]
Jack - this is now released as 0.9.1, including docker, github release, bashly site.

Thanks for yet another insightful idea.
