### ISSUE TITLE
Gem, GitHub release, and Docker image are out of sync

### ISSUE THREAD

**Issue by iamjackg** [DannyBen/bashly#309]
Hey Danny,

Looks like while version 0.9.0 of the gem is out, there is no corresponding GitHub release, and the Docker Hub image is also still on 0.8.10.

**Comment by DannyBen** [comment]
You are absolutely right. These two processes are manual since Docker revoked automatic builds for open source.
I have updated both now, thanks for reporting.

**Comment by iamjackg** [comment]
Yeah, a lot of open source projects have migrated over to [GitHub's own registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry) for that very reason...

Thanks for the prompt response :)
