### ISSUE TITLE
Support setting color for commands 

### ISSUE THREAD

**Issue by yecol** [DannyBen/bashly#310]
### Description

It would be better if users can set commands colors like this:

<img width="498" alt="image" src="https://user-images.githubusercontent.com/426463/206643844-f234226c-c317-4ded-82ec-e32163b9f96c.png">

I didn't find how to set this, or maybe I overlooked something.

**Comment by DannyBen** [comment]
This is not currently possible.

Bashly generates several types of usage formats, and if coloring support is added to it, it should consider more than just the command name.

For example, some people might want to color the `Usage`, `Commands` and `Options` captions below.

```
cli - Sample application

Usage:
  cli COMMAND
  cli [COMMAND] --help | -h
  cli --version | -v

Commands:
  download   Download a file
  upload     Upload a file

Options:
  --help, -h
    Show this help

  --version, -v
    Show version number

Environment Variables:
  API_KEY
    Set your API key
```

If anyone has an idea of how they expect to configure these colors, I am open to considering.

**Comment by DannyBen** [comment]
I have added this feature, see #322 for details or the [colors-usage example](/examples/colors-usage).
It will be released soon.

Thanks for the suggestion, and I hope the implementation fits your needs.
