### ISSUE TITLE
Split config file for commands

### ISSUE THREAD

**Issue by niksfirefly** [DannyBen/bashly#320]
### Description
I wonder if it is possible to split bashly.yml for commands with autogenerate command.yml file.

Solution for my problems:
1.bashly.yml with multiple commands/args is huge

2.I use cookiecutter to generate project with header.yml
```
name: {{ cookiecutter.project_name }}
help: {{ cookiecutter.project_help }}
version: {{ cookiecutter.project_version }}
```
and defaults.yml with global flags
```
flags:
  - &force
    long: --force
    short: -f
    help: Overwrite existing files

  - &verbose
    long: --verbose
    short: -v
    help: More details

  - &debug
    long: --debug
    short: -d
    help: Debug script info
```
So header.yml and defaults.yml are always provided by cookiecutter/cruft across all projects
and commands from files like command.yml
For now I use cat or python solutions to concatenate files from bashly.d dir to bashly.yml

**Comment by DannyBen** [comment]
I am sorry, I do not understand the issue.
Are you using [Bashly Split Config](https://bashly.dannyb.co/advanced/split-config/)?
If so, what is the problem it does *not* help you solve?

It would help to see the smallest possible use case of how you expect it work.
