### ISSUE TITLE
Add mode lines to generated or copied script fragments

### ISSUE THREAD

**Issue by halostatue** [DannyBen/bashly#329]
### Description

By default, `vim` detects `.sh` files as POSIX shell, and detects `.bash` files as Bash. Practically, this is the difference between `declare` and other bashisms being highlighted or not.

This can be mitigated by the addition of a mode line:

```bash
## vim: set ft=bash
## Code here runs inside the initialize() function
## Use it for anything that you need to run before any other function, like
## setting environment variables:
## CONFIG_FILE=settings.ini
##
## Feel free to empty (but not delete) this file.
```

Emacs has extensions which can parse a Vim modeline, but canonically it would be something like:

```bash
## -*- mode: bash -*-
## vim: set ft=bash
## Code here runs inside the initialize() function
## Use it for anything that you need to run before any other function, like
## setting environment variables:
## CONFIG_FILE=settings.ini
##
## Feel free to empty (but not delete) this file.
```

This could be shortened to

```bash
## -*- mode: bash -*- vim: set ft=bash
## Code here runs inside the initialize() function
## Use it for anything that you need to run before any other function, like
## setting environment variables:
## CONFIG_FILE=settings.ini
##
## Feel free to empty (but not delete) this file.
```

Interestingly, my current vim is detecting this as bash:

```bash
## -*- mode: bash -*-
## Code here runs inside the initialize() function
## Use it for anything that you need to run before any other function, like
## setting environment variables:
## CONFIG_FILE=settings.ini
##
## Feel free to empty (but not delete) this file.
```

These can be added at the top or bottom of the generated files.

**Comment by DannyBen** [comment]
Where can I see the documentation for this?

**Comment by halostatue** [comment]
Vim’s documentation has a section [on modelines](https://vimdoc.sourceforge.net/htmldoc/options.html#modeline), but that’s fairly opaque and technical. There’s an [emacs.stackexchange thread](https://emacs.stackexchange.com/questions/36525/is-there-an-emacs-equivalent-of-vims-modeline-magic) which covers the Vim concept and the Emacs equivalent of it, and forms the basis of what I have been doing.

There are packages for both Sublime Text and [VS Code](https://github.com/ctlajoie/vscode-modelines) which provide modeline support, as well.

**Comment by DannyBen** [comment]
You know you can [set your own header](https://github.com/DannyBen/bashly/tree/master/examples/custom-script-header#readme) right?

Or [change the extension of the partials](https://bashly.dannyb.co/usage/settings/)

**Comment by DannyBen** [comment]
Oh I just saw the title again - you want to add this line to the partials, not the generated script....

Either way - I don't think it is needed. I do not know which editor is used by the users, and personally I see no difference when it is opened in vim. I am assuming that changing the extension of the partials will solve any syntax highlighting issues you may encounter.

**Comment by halostatue** [comment]
The script header isn’t where this belongs, because its use of `#! /usr/bin/env bash` *also* tends to be autodetected correctly when editing the generated final script.

This is about making things a little cleaner for editing the generated partials. Changing the extension of the partials would certainly be the easiest way to do this *for me*, but doesn’t help people who run into this problem in the future.

**Comment by DannyBen** [comment]
> but doesn’t help people who run into this problem in the future.

Why not? Most editors do not have any distinction between `.sh` and `.bash`, and even if some editors do, most people don't notice any problem, I am assuming.

If it bothers someone - now or in the future - there is a simple solution. I definitely don't think this case merits polluting the partials with comments for a specific editor.

**Comment by halostatue** [comment]
More editors *should* make a distinction, because what is legal / reserved in `bash` may not be legal in `ash`, `dash`, or `busybox` `sh`. Yes, for standalone scripts, this is generally *properly* detected by the shebang. In terms of developer weight, though, vim and emacs are perhaps the most widely used editors where Bash runs, and far less frequently other editors (although `code` is catching up).

Aside from suggesting it because I think it is a good idea, I’m not particularly invested in whether this feature request is implemented, especially as there is a setting that can fix this for me.

**Comment by DannyBen** [comment]
Perhaps a more appropriate solution would be to change the default extension to `.bash`. But this will be a breaking change.

**Comment by DannyBen** [comment]
> I’m not particularly invested in whether this feature request is implemented

I am going to close this ticket then. I think that if anyone is bothered by it, they should simply change the partials extension in the settings instead of adding editor instructions, but in any case - I leave it to the user to decide.

Maybe 1.0 will use .bash as a default extension.

Thanks for the idea.
