### ISSUE TITLE
Support Private Flags

### ISSUE THREAD

**Issue by halostatue** [DannyBen/bashly#332]
### Description

Right now, only (sub-)commands and environment variables (environment variables require a 'default' value for this to be the case) can be set to private: true and therefore hidden from documentation. This is useful, but occasionally I have flags on commands that I need to exist, but should not be used by default (either they are intended to be used by an internal re-invocation of the script or are options that are dangerous by default).

**Comment by halostatue** [comment]
Created from #330.

**Comment by DannyBen** [comment]
Done.
