### ISSUE TITLE
Custom libraries for `bashly add`

### ISSUE THREAD

**Issue by halostatue** [DannyBen/bashly#333]
### Description

I’m likely to be converting a half-dozen scripts to Bashly, and it would be nice to be able to do something like:

```console
$ bashly add --github halostatue/bashly-library/my-utils
…
```

I can manage this manually, but it would be nice to have this handled automatically.

This is a *revised* feature request from what is in #330 as I believe that *externalizing* the libraries explicitly is better from both a code maintenance and convention perspective, as one would not have to worry about how `$BASHLY_CUSTOM_LIBS` might work, as `bashly add` is a one-off.

**Comment by DannyBen** [comment]
This could be more involved, as the libraries each have some config that tells it how to add itself.

https://github.com/DannyBen/bashly/blob/4f9c9c6469335c9b4a2c0e495ac74c905a6ef310/lib/bashly/libraries.yml#L1-L20

**Comment by halostatue** [comment]
Understood. It’s not something that is needed immediately, and it may impact the design of the library code that already exists. If needed, I can expand on the basic spec below:

1. The command-line specification for a git repo would be `--git git-repo-url[//path][@REF]` (this is similar to the Terraform specification: git-repo-url[//module-path][?ref=REF]). That means `--git https://github.com/halostatue/bashly-library//my-lib` (HTTPS clone) or `--git git@github.com:halostatue/bashly-library//my-lib` (SSH clone). Convenience flags like `--github` or `--github-ssh` could be used.
2. The path provided (it’s optional, so would default to the root of the repo) would have to have a `library.yml` file that would be read. It would contain a single `files:` key, with the array of `{ source:, target: }` exactly as specified above.

Initially, at least, external libraries *may not* have any Ruby extensions, nor would there be a way to specify them. The libraries code could clone the git repo, check out the reference, and then change to the repo directory as specified. If there’s no `library.yml` file present, there’s an error. If the `library.yml` file does not validate the specification above, there’s an error.

Bashly would still refuse to overwrite a target that already exists.

I’d try out a potential implementation in a PR, but I’ve currently got ~5 side projects including the one that I’m using Bashly for, so the time isn’t going to be present for a few weeks.

**Comment by DannyBen** [comment]
I am not yet sure I want to have this feature in bashly. It is a complex re-implementation of simple file copy.

**Comment by DannyBen** [comment]
The majority of the necessary refactoring is done, with support for adding from a local folder:

```
bashly add --source path/to/lib-source add whatever
```

I am planning on adding git/github support as follows:

```
bashly add --source git:repo-url[//path@ref] ...
bashly add --source github:user/repo[//path@ref] ...
bashly add --source github-ssh:user/repo[//path@ref] ...
```

**Comment by DannyBen** [comment]
Implementation is complete. 

You need to create a directory that contains `libraries.yml`, [similar to how it is done internally in bashly](https://github.com/DannyBen/bashly/tree/master/lib/bashly/libraries).
It can be in a local path or git repo.

@halostatue - would you like to test before I release?

**Comment by halostatue** [comment]
I will run some tests and let you know later this evening EST.

**Comment by halostatue** [comment]
Perfect. I just made a couple of example configurations to try for this, so I haven’t had time to make a proper library, but this is *extremely* useful and will make it *much* easier to use for converting a number of complex scripts for work.

Thanks for this feature and a great tool. I’ll let you know when I have things ready. (What’s funny is that I think that I’ve already decided that the script that started me looking at bashly will be ported to Go, but that’s also because I think it should be doing a lot more than it’s doing already, and it’s time to change languages because of that. However, for the various build scripts that I have, this will be *perfect*).

**Comment by DannyBen** [comment]
Alright cool. I just want to add auto upgrade functionality, and docs, and I will release it.

Thanks for verifying.

**Comment by DannyBen** [comment]
I am going to close this issue, the implementation was larger than expected, so I hope it is useful.

I plan on releasing the first feature-stable major release 1.0.0 - so if you have additional possibly breaking change suggestion, this would be a good time.

In any case, thanks for all your feedback.

**Comment by DannyBen** [comment]
Version 1.0.0.rc1 is live with this change.
Documentation: https://bashly.dannyb.co/advanced/lib-source/
