### ISSUE TITLE
Command Validation misses commands named like flags

### ISSUE THREAD

**Issue by halostatue** [DannyBen/bashly#344]
### Bashly Version

Latest Ruby Gem

### Description

This is a little odd, as I was trying to smuggle a command to look like a flag. That is:

```yaml
commands:
  - name: --install
    private: true
```

It doesn’t work, but *where* it failed surprised me: at runtime with `invalid option: --install`, instead of during build and validation of commands.

If Bashly prohibits commands that look like flags, it would probably be good to add validation that *prevents* such. If the prohibition is accidental, then there should probably be a way of handling cases where commands like this are defined.

I would *prefer* it if I could have a command that looks like a flag, or a way of attaching a non-validation function to a flag—but I would be as satisfied to see this explicitly disallowed.

#### Aside: Why I would prefer this as a feature

My use case is that I’m trying to make a self-installing script where you *could* do something like:

```console
$ curl -sSL https://github.com/halostatue/neat-cli/blob/v1.0/neat-cli | bash -- --install
# output that indicates that `neat-cli` has installed itself
```

Or, if one prefers, download `neat-cli` and then run `./neat-cli --install`.

I already have an `install` command which can’t be repurposed for this case.

### Reproduction Steps

1. Create a command called `--install`.
2. Build the script.
3. Run the script with `--install`.

### Actual Behavior

The output is `invalid option: --install`.

### Expected Behavior

Some sort of validation error on the command named `--install`, or that the command `--install` gets run.

**Comment by DannyBen** [comment]
Well, `-anything` as a command will definitely not be supported. 

As for the validation - there are many cases where the validation will pass, and the bashly.yml may still contain errors. The validation does not come to protect against intentional attempts to mess with it, but rather against accidents.

Even though it was not so in your case, I can accept the fact that someone might use a `--flag` format in a command. 

I *might* update the validation accordingly.

**Comment by DannyBen** [comment]
Ok - I added validation, which also prohibits the use of uppercase characters, which causes a weird behavior on its own.

Thanks for the bug report.
