### ISSUE TITLE
 bashly  add completions  error

### ISSUE THREAD

**Issue by dddachui** [DannyBen/bashly#346]
### Bashly Version

Latest Ruby Gem

### Description

use `docker run --rm -it --user $(id -u):$(id -g) --volume "$PWD:/app" dannyben/bashly `
and when  `bashly  add completions`  error

`https://bashly.dannyb.co/advanced/bash-completion/#bashly-add-completions` 
error for this
```shell
[ikunOS] 09:52:14 root@dev ~/project/bashly-test bashly  add completions
Usage:
  bashly add colors [--force]
  bashly add comp FORMAT [OUTPUT --force]
  bashly add config [--force]
  bashly add lib [--force]
  bashly add settings [--force]
  bashly add strings [--force]
  bashly add test [--force]
  bashly add validations [--force]
  bashly add yaml [--force]
  bashly add (-h|--help)
```

### Reproduction Steps

 bashly  add completions

**Comment by dddachui** [comment]
The three ways I read the document report errors. Is it my operation problem

**Comment by dddachui** [comment]
OS： centos7.9
ruby : ruby 2.0.0p648 (2015-12-16) [x86_64-linux]

**Comment by dddachui** [comment]
ok, i know ,thank you very much!!

**Comment by DannyBen** [comment]
Sure thing - sorry for the confusion, and thanks for taking the time to report.

**Comment by dddachui** [comment]
did this "Bash Completion" same as linux's "bash-completion" ,when i click the `TAB` to complete the command automatically?

**Comment by DannyBen** [comment]
the `bashly add completions` (or `bashly add comp` in the old version) adds a completions function that provides tab completion. See https://bashly.dannyb.co/advanced/bash-completion/

You can either create a standalone completions script, or a function that is a part of your bashly-generated bash script.
If you do the function, there are a couple of additional steps you need to take, as noted in the documentation.
