### ISSUE TITLE
bashly about “The goal is to generate a new file and fill it with many variables”

### ISSUE THREAD

**Issue by dddachui** [DannyBen/bashly#358]
Use bashly to create a subcommand. In the shell,
```shell
cat>file.txt<<EOF
content
EOF
```
But it cannot be executed after `bashly ge`
The goal is to generate a new file and fill it with many variables

**Comment by DannyBen** [comment]
I am not sure I understand the problem.

But, if you are using Heredoc in your bashly script, then you need to enable tab indentation in the bashly script.
By default, bashly uses spaces for indentation, which does not work well with heredoc.

See if these help:

1. [Setting `tab_indent` in settings](https://bashly.dannyb.co/usage/settings/#tab_indent
2. [Heredoc example](https://github.com/DannyBen/bashly/tree/master/examples/heredoc#readme))
3. [Heredoc alt example](https://github.com/DannyBen/bashly/tree/master/examples/heredoc-alt#readme)

Note that this tab indent setting can be set either via the settings.yml or an environment variable, as described [here](https://bashly.dannyb.co/usage/settings/#environment-variables).

**Comment by DannyBen** [comment]
I have made heredoc work naturally, without the need to do anything (#496). bashly will no longer apply additional indentation to the strings inside a heredoc block.

This is available in the edge version, if anyone wishes to test it.
