### ISSUE TITLE
Flags should not be set to their default value if not explicitly used

### ISSUE THREAD

**Issue by ChipS3t** [DannyBen/bashly#369]
If an optional flag is not explicitly used, the default value should not be set. If the flag was not provided, the script can perform one action. If the flag was provided, but an argument was not specified, the default value should be set.

I noticed this issue when creating a script that would use a local copy of a file by default, but if the user passed the `-d` option, the script would fetch a different one from a website. The script provided a default location to fetch the alternate file contents, but the user could also pass in their own address. However, since the flag was set to its default value, regardless of whether the user used that flag, the script would always fetch the alternate file.

**Comment by DannyBen** [comment]
No. We have different interpretation of default alue.
I am using the same interpretation as used in [docopt](http://docopt.org/) - if **not** provided by the user, the variable you get has a default value.

If a flag needs an argument, it cannot be provided without a value. It can either be provided in full, or not at all.

**Comment by ChipS3t** [comment]
You are correct. I was unable to find a single instance of a command that has the behavior I described:

1. The command has some default behavior associated with it
2. Specifying a flag (e.g. -e --exclude) with no argument changes this default behavior with a different default behavior associated with the flag
3. Optionally, an argument can be provided to the flag to overwrite the default behavior of the flag (e.g. -e file --exclude=file)

Furthermore, it could cause confusion if such a command did exist without informing the user that the position of the flag within the command is important. For example, let's say a fictional command had the following usage: `excommand [file] -v [pattern]`. Using `excommand` would perform some default action, specifying the `-v` would change this default action, and specifying `-v pattern` would provide an argument to the flag to overwrite the flag's default action. If a user used the command like this: `excommand -v file.txt`, how would the command know whether `file.txt` was an argument to the flag or was meant as the `file` argument? You could inform the user that nothing is allowed to come after the `-v` option except an optional argument to the flag, but this would be confusing and not particularly elegant.

There are two ways I can think of to implement the behavior I want:

1. Use two different flags. One that specifies the default option and another to overwrite that default option. You could also make these flags mutually exclusive if you wanted. I don't really like this behavior much. It feels redundant and confusing.
2. Make the argument to the flag required and provide a special value that acts as a default. For instance, you could have a flag that takes a URL or the keyword "default". If you provide "default" to the flag, the script would change the value to the default URL; otherwise, it will use the user-provided URL.

**Comment by DannyBen** [comment]
Well, a few points:

1. In bashly, the flag behavior in this regard is unlikely to change. Meaning, a flag can either have an argument or not. There will be no "hybrid" flags. I have seen this been done in some more rare places, but I do not believe this is a good practice.
2. If you have a specific real life use case that you want my opinion on, I am happy to help - I just need more details, and possibly the most minimal bashly YAML file to demonstrate why this is needed.

On a personal note: As both a heavy user and builder of command line interfaces, I never encountered a situation that required the discussed behavior, and where I *did* see such behavior, it felt like an unnecessary shortcut that could have been communicated more clearly using two different flags.
