### ISSUE TITLE
Whitespace not respected in here documents

### ISSUE THREAD

**Issue by ChipS3t** [DannyBen/bashly#374]
### Bashly Version

Latest Ruby Gem

### Description

Creating a here document such as this:
```
cat << EOF
a
b
c
EOF
```
will result in an error due to the whitespace in front of the EOF. It will also add additional whitespace in front of the lines. See [ShellCheck](https://www.shellcheck.net/wiki/SC1039) for more details.

### Reproduction Steps

Create a `root_command.sh` file with the following contents:
```
cat << EOF
a
b
c
EOF
```
Run the script

### Actual Behavior
An error similar to this:
```
./bashly-test: line 214: warning: here-document at line 17 delimited by end-of-file (wanted `EOF')
./bashly-test: line 215: syntax error: unexpected end of file
```

### Expected Behavior
Prints the following:
```
a
b
c
```

**Comment by DannyBen** [comment]
You need to:

1. Use `<<-` instead of `<<`
2. Instruct bashly to generate with tabs instead of spaces

See:

- [Two heredoc examples](https://bashly.dannyb.co/examples/#other-examples)
- [Settings](https://bashly.dannyb.co/usage/settings/#tab_indent)
