### ISSUE TITLE
shdoc integration

### ISSUE THREAD

**Issue by guilhermeprokisch** [DannyBen/bashly#414]
### Description

I think it could be a nice idea to integrate bashly with shdocs for documentation generation

https://github.com/reconquest/shdoc

**Comment by DannyBen** [comment]
Thanks for the suggestion. I looked at it, and here are my issues:

1. It seems to be more geared towards describing "source code" (functions) and not optimized for describing a CLI.
2. If using it in bashly, it will just mean that we put one huge comment at the beginning of the file (which will be a part of the "production ready" script), which is far from ideal.
3. I am not a huge fan of its syntax nor its output.
4. I am not sure I see the advantage of having a markdown file that simply describes the same thing as `your-program --help`.

---

If anything - I think it *might* be nice to generate documentation from the bashly.yml file in a more generic way - for example, as requested in #69 - to generate man pages. So, ideally, we would have some command that generates anything using templates. It can be markdowns, or man pages, or whatever - with user customizable templates.

I will take another look at it.

**Comment by DannyBen** [comment]
@guilhermeprokisch - I have a proposal discussed in https://github.com/DannyBen/bashly/discussions/415, in case you wish to chime in.

**Comment by DannyBen** [comment]
The [edge](https://github.com/DannyBen/bashly/tree/master/edge#testing-unreleased-edge-bashly-versions) version now includes a `bashly render` command.

You can run `bashly render :markdown docs` to get a `docs` directory with markdown documents for each command.
To see these documents as HTML, you can use [madness](https://github.com/DannyBen/madness).

There is still work to do, but this is good progress.
If there are any comments about the output, this is the time.
If you wish to see the template used to generate these markdowns, it is [here](https://github.com/DannyBen/bashly/tree/master/lib/bashly/views-alt/markdown)

**Comment by DannyBen** [comment]
Done. See https://github.com/DannyBen/bashly/discussions/415#discussioncomment-6823404

**Comment by DannyBen** [comment]
Version 1.1.0 is released with markdown and manpage rendering.

Run `bashly render --help` for more information, or [read the docs](https://bashly.dannyb.co/advanced/rendering/).

**Comment by guilhermeprokisch** [comment]
Thanks for the effort @DannyBen  I will test it out
