### ISSUE TITLE
Allow generating Dash shell/POSIX shell code instead of Bash via some config option or CLI flag

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [DannyBen/bashly#425]
### Description

https://manpages.ubuntu.com/manpages/focal/en/man1/sh.1.html

There is no such thing for Dash (which I personally use for fast, portable and minimal scripts).

**Comment by DannyBen** [comment]
You will have a long life. I just sat down and wanted to ask you something about the JSON schema.

> Allow generating Dash shell/POSIX shell

1. I don't see how this will be an easy endeavor - See the [views](https://github.com/DannyBen/bashly/tree/master/lib/bashly/views) directory - these are all the templates used for generating the bash script.
2. I am probably missing something in regards to the use case: The generated scripts come with a shebang, so they should run everywhere there is bash. Are you talking about running them in places without bash? Why not install bash instead? It is easily installable everywhere.
3. Bashly actually uses features that exist in bash. Having to generate a complex script without some of these features will be much harder.
4. I am just working on a feature that allows rendering the bashly data structure as anything you want using either built in templates, or custom templates - see https://github.com/DannyBen/bashly/discussions/415 - it is currently available in master branch and allows rendering markdown docs and man pages. Perhaps this can be used for it? To render a smaller script?

---

My completely off-topic question to you: I want to allow the bashly.yml file to include arbitrary data keys, like docker-compose allows it. My thought is to copy the same naming convention: If it starts with `x-`, it is allowed to exist (and contain any data structure, even hashes and arrays). Can we update the schema to allow it?

**Comment by EmilySeville7cfg** [comment]
> I am probably missing something in regards to the use case: The generated scripts come with a shebang, so they should run everywhere there is bash. Are you talking about running them in places without bash? Why not install bash instead? It is easily installable everywhere.

Dash is lighter than Bash and used for performant scripts. It's mostly for scripting, not interactive usage: Dash should be compiled in a special way to have Emacs/Vi modes for interactive session AFAIK.

> Bashly actually uses features that exist in bash. Having to generate a complex script without some of these features will be much harder.

Is it possible to implement the ability to write extensions for Bashly to add any POSIX-like language support?

**Comment by DannyBen** [comment]
> Dash is lighter than Bash

Yes - but am I right in guessing that it is a completely different script, and that you might not need (or even be able to) implement all that bash has to offer? I mean - can the fully featured bashly.yml be converted to a dash script, with args, flags and so on?

> Is it possible to implement the ability to write extensions for Bashly to add any POSIX-like language support?

Not now.
But, I need more details to be able to contribute to this discussion.

Like:

1. Do we want to have all the features that exist in bashly.yml, and just output a script in a totally different language?
2. Or, will it have to be a different bashly.yml, with less (or other) features?
3. Where can I see a real life, typical dash script?

In addition - you can use bashly now (the master branch) to render anything - including Dash scripts.
This at least lets you perhaps prototype something, and then I can understand your train of thought better.

---

In case you do want to try custom renders on your own, follow these steps:

1. Get and install the master version (see [edge](https://github.com/DannyBen/bashly/tree/master/edge#using-ruby)).
2. In some empty folder, run `bashly add render_markdown` - it will add the rendering templates
3. Update the gtx template, and run `bashly render templates/markdown output_path`

**Comment by EmilySeville7cfg** [comment]
> I mean - can the fully featured bashly.yml be converted to a dash script, with args, flags and so on?

It can be, but it requires more work. For instance, there are no arrays in Dash except "$@", so they should be emulated.

> Do we want to have all the features that exist in bashly.yml, and just output a script in a totally different language?

Personally, I want exactly this thing.

**Comment by DannyBen** [comment]
> there are no arrays in Dash except "$@"

Whoa... bashly relies heavily on arrays and associative arrays.
They are how you access the input that was provided by the user - for example `${args[--force]}`.

> Personally, I want exactly this thing.

Then I need to see some prototype using the custom template renderer. I am unlikely to bite otherwise 😉

**Comment by DannyBen** [comment]
I am closing this, as it is unlikely to happen.

If there is (much-) more demand for it, and someone is willing to undertake the majority of the workload (especially in the templating aspect), we can open a discussion.
