### ISSUE TITLE
Implement 'all' Command for Sequential Execution of All Commands

### ISSUE THREAD

**Issue by m18unet** [DannyBen/bashly#435]
### Description

Hello, 

I have 3 commands named `pod`, `service`, `pvc`. I want to add a fourth command called `all`. When I execute `all` I want the other 3 commands to be executed in order.

Is that possible?

**Comment by DannyBen** [comment]
Yes it is possible, but probably not in the way you think.

Implementing such a solution in a generic way, would be problematic. There are arguments, and flags, and possibly other requirements for each of your commands - so what will the `all` command do? How will it supply these arguments? How do you ensure that the requirements for all the "child" commands are met?

So - you have several options:

### Option 1: Call your other commands by re-running the CLI

Your `all` command can simply run your own command, as you run any other linux command. Assuming we have `build` and `deploy` command, and now a new `all` command:

```bash
# src/all_command.sh
./cli build --force
./cli deploy eu-east
```

### Option 2: Use functions

If you are familiar with Model-View-Controller architecture, treat the code that you write in the `src/*_command.sh` as if it is a controller code. It means, it should be a "dumb" short piece of code, that just calls other functions (a "model" stand in). Then, your `all` command can also call these functions.

For example:

*The basic commands*

```bash
# src/build_comnmand.sh
build_project

# src/deploy_command.sh
region=${args[region]}
deploy_project "$region"
```

*Functions*

```bash
# src/lib/build_project.sh
build_project() {
  echo "BUILDING..."
}

# src/lib/deploy_project.sh
deploy_project() {
  region="$1"
  echo "DEPLOYING TO $region..."
}
```

*The `all` command*

```bash
# src/all_command.sh
build_project
deploy_project "eu"
# or, if your `all` command also has arguments
deploy_project "${args[region]}"
```

Does this help?

**Comment by DannyBen** [comment]
My pleasure. Enjoy, and feel free to open an issue or a discussion if you have any problems or questions.
