### ISSUE TITLE
gem install bashly in wsl1

### ISSUE THREAD

**Issue by dddachui** [DannyBen/bashly#438]
Building native extensions. This could take a while...
ERROR:  Error installing bashly:
        ERROR: Failed to build gem native extension.

    current directory: /usr/local/share/gems/gems/stringio-3.0.8/ext/stringio
/usr/bin/ruby -I /usr/share/rubygems extconf.rb
mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h

You might have to install separate package for the ruby development
environment, ruby-dev or ruby-devel for example.

extconf failed, exit code 1

Gem files will remain installed in /usr/local/share/gems/gems/stringio-3.0.8 for inspection.
Results logged to /usr/local/lib64/gems/ruby/stringio-3.0.8/gem_make.out

**Comment by DannyBen** [comment]
This is not a bashly specific issue, but rather a Ruby on WSL issue, which is beyond the scope of what I can help with.

However, it looks like the Ruby installation does not include the necessary system tools for building Ruby gems.
For Ubuntu systems, a proper Ruby installation includes these OS packages (install with `apt`):

```
autoconf
build-essential
libffi-dev
libgdbm-dev
libreadline-dev
libreadline-dev
libssl-dev
libyaml-dev
```

You can try to install `ruby-dev` or `ruby-devel` if such package exists.

**Comment by dddachui** [comment]
sorry sir，wsl needs install gcc make  libyaml-devel   It's my fault

**Comment by DannyBen** [comment]
No worries. Usually, in most Linux distributions, there is a package that installs `gcc` and `make` and similar tools.
In Ubuntu it is `build-essential`.
