### ISSUE TITLE
Keep comments in ini config file

### ISSUE THREAD

**Issue by Linbreux** [DannyBen/bashly#450]
### Description

Hey,

First of all, really handy peace of software!

I created a `config.ini.example` file and it has comments to describe what each feature does and how it should be configured. This example file is copied to a `config.ini` file. When we change a variable using the `ini_save` command. It saves everything correctly, but the order is changed and all the comments are gone. Is it possible to keep them when using the `ini_save` command and as a bonus also maintaining the original order?

Thanks!

**Comment by DannyBen** [comment]
Thanks. I am happy you find it useful.

You can see my reply to a similar question here: https://github.com/DannyBen/bashly/issues/416#issuecomment-1690970892
