### ISSUE TITLE
Update bashly schema to support `flag.unique` and `arg.unique`

### ISSUE THREAD

**Issue by DannyBen** [DannyBen/bashly#457]
See #454 and #456.

Both Argument and Flag now support a new boolean option named `unique`.
The JSON schema needs to be updated accordingly.

**Comment by DannyBen** [comment]
@EmilyGraceSeville7cf - do you have time for this?

**Comment by EmilyGraceSeville7cf** [comment]
Hey. Yeah, I guess I can do it tomorrow.🙂
