### ISSUE TITLE
Package external files with the generated bashly command

### ISSUE THREAD

**Issue by user-name-is-taken** [DannyBen/bashly#460]
### Description

It would be nice to package files with the generated command. For example, I want to include scripts and binaries that I could run from within a bashly command. Another example would be to package sample data for programs that do data processing.

**Comment by DannyBen** [comment]
I am not sure I understand.

- If you want to include text in your script, you should put it inside functions inside the [`lib`](https://bashly.dannyb.co/usage/writing-your-scripts/#adding-common-functions) directory.
- I cannot imagine how would a "including binaries" work, but there is the ability to require that a program is installed on the running machine: [`command.dependencies'`](https://bashly.dannyb.co/configuration/command/#dependencies)

**Comment by user-name-is-taken** [comment]
It's more like have the script generate a directory that contains the bashly script along with any other artifacts the bashly script needs.

**Comment by DannyBen** [comment]
This is outside the scope of bashly. It seems like you are looking for an installation script. Bashly cannot know where these artifacts are coming from.

Generating package manager packages (.deb, .rpm) is definitely out of scope.
