### ISSUE TITLE
Add key-value parameters

### ISSUE THREAD

**Issue by user-name-is-taken** [DannyBen/bashly#482]
### Description

Add the ability to parse key value pairs for parameters. For example I want to be able to do this:

```
command --flag flagKey=flagValue --flag flagKey2=flagValue2
```

or this 

```
command argKey=argValue argKey2=argValue2
```

It would also be good to have `allowedKeys` and `allowedValues` lists so the keys and/or values can be validated similar to how flags and args are currently validated.

**Comment by DannyBen** [comment]
1. This is very nonnstandard. Can you share examples of one or two notable command line tools that do it?
2. This requires a nested dictionary as the receiver: `args[--flag][flagKey]=flagValue`, which does not exist in bash.

**Comment by user-name-is-taken** [comment]
Here are some of the examples that came up when used `man --regex -K "\-\-[a-z]+ [a-z]+\="` to search for key=value flag options

```
parallel --template file=repl
pandoc --metadata cls=FILE
gcc --param name=value
dh_installdeb --define TOKEN=VALUE
as --defsym sym=val
thin_dump --format
kubectl
cmake -Werror=deprecated
kubectl config view -o jsonpath='{.users[].name}'
```

Key-value argument options I feel are more common, but are also more difficult to search for. Here's an easy example I could think of:

```
env key=value
```

**Comment by DannyBen** [comment]
Well - nothing in bashly prevents you from doing this. The only difference is terminology.

From a framework perspective, your x=y pairs are values, either for a flag, or as an argument:

```bash
command  argument=value  --flag key=value      
         +------------+         +-------+
         arg value              flag value
```

Parsing these further to extract the two sides of the key=value pair is left up to you.

Bashly conforms to this standard:

- one dash for short flags
- two dashes for long flags
- everything else is an argument

and supports these alternative formats:

- -abc same as -a -b -c
- -a=arg same as -a arg
- --flag=arg same as --flag arg
---

As there is no data structure in bash that can hold this nested dictionary - I am curious, how do you expect to receive this user input?

In a richer language, I would expect `--flag key=value` to be optionally parsed into a nested hash:

```ruby
args = {
  '--flag' => {
    'key' => 'value'
  }
}

# or in other words:
args['--flag']['key'] = 'value'
```

but this cannot be done in bash.

At any rate, I believe you should use one of these options:

- [library functions](https://bashly.dannyb.co/advanced/library/) - to define this type of parsing in one place, as a reusable function.
- [function hooks](https://bashly.dannyb.co/advanced/hooks/#function-hooks) - in case you always want to run something before function execution (like additional parsing).
- [custom filters](https://bashly.dannyb.co/advanced/filters/#custom-filters) - in case you wish to validate the input is in the format you want them to be, with a filter that is not already supported natively.

**Comment by user-name-is-taken** [comment]
As far as I see it there are 2 good options for how to receive the input: 

1. As environment variables
2. As an array of [key,value,key,value].... This option may be better because it would allow you to do something like `command --flag key=value,key=value,key=value` which would also be useful for people who want to do `command --flag value1,value2,value3` instead of `command --flag value1 --flag value2 --flag value3`

**Comment by DannyBen** [comment]
No, none of these are good in my opinion.

1. Environment variable is just a string - further parsing will be warranted, so you better parse the value of `${args['--flag']}` as it was provided already by bashly.
2. This is yet another invented structure that requires users of bashly to understand, and yet again parse themselves.

Nothing stops you from having any value (with equal signs, commas) in bashly. However, how you parse it and how you store it is up to you, and should be quite easy, especially using one of the facilities I mentioned earlier.

**Comment by DannyBen** [comment]
I have created the [key-value-pairs example](https://github.com/DannyBen/bashly/tree/master/examples/key-value-pairs#key-value-pairs-example) to demonstrate how to easily support key=value pairs either for arguments or flags.

Hope this helps.
