### ISSUE TITLE
Add option to disable splitting of flags with value for catch_all arguments

### ISSUE THREAD

**Issue by MIOB** [DannyBen/bashly#510]
### Description

Hi,

first of all, thank you for this project. It is really marvelous. There are not so many good tools for bash scripting, and finding such a gem was really nice.

One of my commands is supposed to execute the binary (specifically bazel) and pass all unparsed arguments to it. I use catch_all for that, e.g., something like that:
```yml
commands:
  - name: test
    catch_all:
      label: arguments
      required: true
```
And the test.sh:
```bash
(
cd "$MY_PROJECT_DIR"
bazel test "${other_args[@]}"
)
```
And everything works fine except one thing: bazel accepts their flags in the format `--key=value`. And bashly splits such flags to `--key` and `value`, so, when I run something like `mycli test --cache_test_results=no my-target`, it becomes `bazel test --cache_test_results no my-target`. And bazel does not understand such format and treats `no` as a target, not as a value of --cache_test_results.

It would be nice to have an option that disables such splitting for catch_all arguments or, if it is difficult, to disable the format `--flag=value` at all. 

Right now, I have added the following `initialize.sh` as WA to my script:
```bash
function normalize_input() {
  local arg flags

  while [[ $# -gt 0 ]]; do
    arg="$1"
    if [[ $arg =~ ^-([a-zA-Z0-9][a-zA-Z0-9]+)$ ]]; then
      flags="${BASH_REMATCH[1]}"
      for ((i = 0; i < ${#flags}; i++)); do
        input+=("-${flags:i:1}")
      done
    else
      input+=("$arg")
    fi

    shift
  done
}

```

**Comment by DannyBen** [comment]
Yes. I see the problem.

At first glance, I agree with you that the splitting should not be done in `catch_all` - but this will probably be a problem.
The parsing and splitting of the arguments is done before bashly knows where each argument goes. First normalize, then decide where they belong.

You will notice that also `-abc` becomes `-a -b -c`.

One thing that I definitely expected to work, was this:

```bash
 ./cli -- -abc --key=value
```

...but it also splits.
(Note the use of the "ignore arguments from this point on" marker `--`)

I think I might be able to implement the latter - will that help?

**Comment by MIOB** [comment]
> I think I might be able to implement the latter - will that help?

Yes, it will help. 

> You will notice that also -abc becomes -a -b -c.

Yes, I also noticed it. But I, at least, can disable it with compact_short_flags. Which, as far as I understand just remove an if from normalize_input. So something that removes these two ifs also helps:
```bash
    if [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
      input+=("${BASH_REMATCH[1]}")
      input+=("${BASH_REMATCH[2]}")
    elif [[ $arg =~ ^(-[a-zA-Z0-9])=(.+)$ ]]; then
      input+=("${BASH_REMATCH[1]}")
      input+=("${BASH_REMATCH[2]}")
...
```

**Comment by DannyBen** [comment]
Alright cool.

I have already implemented it in #511 which seems to be working fine.
I want to add specs, and see if there is any additional tweaks to help the use case you are describing.

The fact that arguments after `--` are parsed at all is definitely a bug.

**Comment by DannyBen** [comment]
>  So something that removes these two ifs also helps:

I need to think about it. In general, there should be no reason to disable any of them - not even the short flags.
The reason being this: All flags (strings that start with -) are parsed by bashly. If there is a need to pass them elsewhere, then they should be preceded by `-- ` - which is exactly why it was born in the first place.

So - I wonder if now that the `--` is fixed, perhaps the compact flags option should be **removed**.

**Comment by DannyBen** [comment]
I have decided to add a `conjoined_flag_args` setting, that when set to `false`, will disable the `--flag=arg` parsing case.

So, in effect, when disabling both `compact_short_flags` and `conjoined_flag_args` - the normalization is completely disabled.

Thoughts?

**Comment by pcrockett** [comment]
I came here today just for this feature... I'll test it out now! Thanks.

**Comment by pcrockett** [comment]
I haven't tested `conjoined_flag_args`, but everything else seems to work fine from my side. Exactly what I was looking for. :rocket:

**Comment by DannyBen** [comment]
Excellent, thanks for reporting.
