### ISSUE TITLE
Bashly generated script fails shellcheck rule SC2059

### ISSUE THREAD

**Issue by ichoosetoaccept** [DannyBen/bashly#547]
Not a huge deal but since the Bashly docs claim that Bashly generates shfmt and shellcheck compliant scripts I thought I'd point this out.

In a script I just generated I get a bunch of warnings for:
Don't use variables in the printf format string. Use printf '..%s..' "$foo". shellcheck(SC2059)

**Comment by DannyBen** [comment]
We stand behind our claims, so if it fails - it is a big deal.
All the generated [example scripts](https://github.com/DannyBen/bashly/tree/master/examples) as well as the secondary (internal) examples in [spec/fixtures/workspaces](https://github.com/DannyBen/bashly/tree/master/spec/fixtures/workspaces) pass both shellcheck and shfmt, as can be seen in [the CI logs](https://github.com/DannyBen/bashly/actions/runs/10389529144/job/28767746994).

If you see otherwise, I need a way to reproduce.

Specifically in regards to SC2059 - as far as I know, all generated code uses the correct format.

**Comment by ichoosetoaccept** [comment]
Here's the offending output in the final script Bashly generated:
```
# :environment_variable.usage
    printf "  %s\n" "LOG_DIR"
    printf "    Directory for storing log files\n"
    printf "    Default: ${RELEASES_FOLDER}/logs\n"
    echo

    # :environment_variable.usage
    printf "  %s\n" "CURRENT_LOG_FILE"
    printf "    Path to the current log file\n"
    printf "    Default: ${LOG_DIR}/current.log\n"
    echo
```

and here's what I have in my bashly.yml:
```
 - name: RELEASES_FOLDER
    help: Path to the releases folder
    default: /export/home/iljazovici/releases
 - name: LOG_DIR
    help: Directory for storing log files
    default: ${RELEASES_FOLDER}/logs
 - name: CURRENT_LOG_FILE
    help: Path to the current log file
    default: ${LOG_DIR}/current.log
```

**Comment by DannyBen** [comment]
Yes. This is because you are using "${RELEASES_FOLDER}/logs" in your bashly.yml string. This entire string is put into the left side of the `printf`. Not much I can do about it, and I advise against such usage.

**Comment by ichoosetoaccept** [comment]
Got it. Thanks!

**Comment by ichoosetoaccept** [comment]
My thinking is that the default value for the format and location of an environment variable called LOG_FILE might depend on the value of another environment variable, say, RELEASE_FOLDER. To achieve this I used variable expansion inside bashly.yml because it saves me from having to initialize the variable elsewhere.
I've now removed the variable expansion and am moving initialization of the affected env vars to my initialize.sh.

I do see a use case here but cannot say if it's worth exploring further since the workaround to avoid this is simple.

In general I figure that the more Bashly can do for me while I'm still in bashly.yml, the better.

**Comment by DannyBen** [comment]
Yes. Your use case was a reasonable one.
The `initialize.sh` is not a good place for it - since it will avoid showing usage if the environment variable is not set.

If at all - it is better to use the `before.sh` file.

**Comment by ichoosetoaccept** [comment]
Ahh.. I misunderstood the docs about before.sh before. I thought anything in before.sh would be executed before calling any function in the final script.. I guess that wasn't too logical of me.
Before a COMMAND is run, that is, before any command that is defined as such in bashly.yml, that makes sense. Thanks!

**Comment by DannyBen** [comment]
Keep the issue open - I will see if there are sufficient places where `printf` can be converted to `echo -e` to allow this use case, at least in some places.

**Comment by DannyBen** [comment]
Ok, I think this (#549) should work. I have changed the way `default`, `allowed`, `conflicts` and `needs` are printed.

```bash
# before
printf "{{ the string }}\n"

# after
printf "%s\n" "{{ the string }}\n"
```

Which should allow using `$SHELL_VARS` in the usage string of these YAML definitions.

For any future discussion that may arise around this subject, here is a summary of printing options in bash, and why we can/can't use each:

### `echo -e`

- Generally advised against, in favor of `printf`, for compatibility reasons mostly. Not sure how true it still is, but we are following this guideline.

### `printf "%s" "{{ external_string }}"`

- **Good** when the external string may contain bash `$variables` or `$(color)` functions (shellcheck violation SC2059).
- **Bad** when the external string may contain newlines (e.g. multi-line help)

### `printf "{{ external_string }}"`

- **Bad** when the external string may contain bash `$variables` or `$(color)` functions (shellcheck violation SC2059).
- **Good** when the external string may contain newlines (e.g. multi-line help)

There may be a fourth option that caters to all three needs, I just haven't found it yet.

**Comment by DannyBen** [comment]
Version 1.2.2 is out, with some changes to how some strings are printed.
The use case in question (`default: ${LOG_DIR}/current.log`) should now pass shellcheck also.

Thanks for bringing that up.
