### ISSUE TITLE
Allow semi-private commands

### ISSUE THREAD

**Issue by mcblum** [DannyBen/bashly#548]
### Description

Hello! First, thank you for Bashly. It has honestly made me enjoy writing Bash which... I never thought possible.

Perhaps it already supports this, but what do you think about allowing a specific flag or env variable or something to expose the private commands in the help text? I have an interesting case where customers really should only see the 4 or 5 commands they need, whereas TAC should be able to see everything. 

Does this sound possible / useful and/or does it already exist in Bashly?

Thanks again!

**Comment by DannyBen** [comment]
This sounds useful, definitely.

Originally, the goal of `private` commands was to allow two primary use cases:

1. Provide lower level commands, to be used by the CLI itself (think git porcelain / plumbing)
2. Provide a place for legacy or deprecated commands.

You are proposing a third use case: Commands for advanced users.

I like it.

But - I prefer not to add to the cognitive complexity of the developer, by adding a "semi private" mode.

How would you feel about just setting an environment variable to show all private commands?

**Comment by mcblum** [comment]
Thank you for the extremely-fast reply! I think your solution sounds great. It would work perfectly, too, because I could make a private command which just sets an env variable and then re-calls itself. At least I think that will work. But yes, that would be amazing!

**Comment by DannyBen** [comment]
> I could make a private command which just sets an env variable and then re-calls itself

Can you give me an example command you would use? The better I understand your requirements, the better the solution will be.

**Comment by DannyBen** [comment]
This is now implemented in #550.

I named that settings key `private_reveal_key`. If there is a better suggestion, this is the time to suggest it.

What is left to do (other than the PR checklist), is to update how mandoc, markdown, and completions are generated. Right now they only consider public commands, but I will probably have them consider all commands when this setting is enabled.

**Comment by DannyBen** [comment]
Version 1.2.2 is out with this change. 
Thanks for the suggestion.
