### ISSUE TITLE
 eval in .zshrc triggers initialise.sh unexpectedly – Is this intended behavior?

### ISSUE THREAD

**Issue by Linbreux** [DannyBen/bashly#558]
Hi,

I'm encountering an issue with a script I added to my initialise.sh file. The purpose of the script is to perform some checks and print a message, it includes a guard so that it only runs once after a reboot, and only when my Bashly program is executed for the first time.

However, due to the following line in my `.zshrc` file:

```
eval "$(<script> completions)"
```
I'm seeing the following error when starting a new shell:

```
(eval):2: bad pattern: ^[[34m╔════════════════════════════════════════╗^[[0m
```
It seems like the completions are causing the initialise.sh script to run earlier than expected.

My question is:

- Is it the intended behavior that completions are triggering the initialise.sh script?
- Is there an alternative approach I could take to ensure that the script only runs the first time I manually execute the program, rather than during shell initialization?

Any advice or suggestions would be greatly appreciated!

Thanks in advance!

**Comment by DannyBen** [comment]
I am not sure I completely understand the issue.

When you say you have this in your `.zshrc`:

```bash
eval "$(<script> completions)"
```

you mean, `<script>` is the bashly generated script?

If so - of course it will call the `initialize` function. The `initialize` function is always called, whenever you run the script, and it is the first thing getting called - look at your generated script, at the bottom.

Your initialize function should include only simple things that are needed by all (or most) of the other functions in your script.

Based on the information given - the only advice I can have is to move whatever you have placed in `initialize` to a different place. If you share its contents, I may be able to help further.

**Comment by Linbreux** [comment]
Hi @DannyBen 

> you mean, <script> is the bashly generated script?  

Yes, indeed.

> Based on the information given - the only advice I can offer is to move whatever you have placed in initialize to a different place. If you share its contents or purpose, I may be able to help further.

It indeed may not be the correct place. I'm doing a version check against an github gist. To notify the user to update if a new version becomes available. Thats the reason why I want to only run it once, so that I'm not spamming the end user.
This is the code I currently have inside my `initialize.sh`:

```bash
CHECK_VERSION_FILE="/tmp/checkversion"
VERSION_URL_REMOTE="<github gist url>"

check_version() {
	set +e
	if [ ! -f "$CHECK_VERSION_FILE" ]; then
		# creating file, to not show the message again until reboot
		touch $CHECK_VERSION_FILE

		remote_info=$(curl -s $VERSION_URL_REMOTE)
		if [ $? -eq 0 ]; then
			remote_full_version=$(echo $remote_info | jq '.last_version')
			remote_version=$(echo $remote_full_version | sed -nr 's/^\"*([0-9]+\.[0-9]+\.[0-9]+)([a-z])?\"*$/\1/p')
			remote_kind=$(echo $remote_full_version | sed -nr 's/^\"*([0-9]+\.[0-9]+\.[0-9]+)([a-z])?\"*$/\2/p')

			this_version=$(version_command)

			version=$(echo $this_version | sed -nr 's/^([0-9]+\.[0-9]+\.[0-9]+)([a-z])?$/\1/p')
			kind=$(echo $this_version | sed -nr 's/^([0-9]+\.[0-9]+\.[0-9]+)([a-z])?$/\2/p')

			release_notes=$(echo $remote_info | jq -r '.release_notes_last_version[]')

			declare -a release_notes_list

			while IFS= read -r line; do
				release_notes_list+=("$line")
			done <<<"$release_notes"

			if [ "$(printf '%s\n' "$remote_version" "$version" | sort -V | tail -n1)" != "$version" ]; then
				# new version available
				gum style \
					--foreground 4 --border-foreground 4 --border double \
					--align center --width 40 --margin "1 2" --padding "1 2" \
					"New Version available! v${remote_version}"

				gum style "Release notes:" --bold --foreground="4"
				for i in "${release_notes_list[@]}"; do
					gum style "  - $i" --foreground="4"
				done
				echo
				gum style --bold --foreground 4 "Navigate to the folder and checkout the master branch or 'v${remote_version}' tag"
				echo
			fi
		else
			echo "No network connection. Unable to check for new version."
			rm $CHECK_VERSION_FILE
		fi
	fi
	set -e
}

check_version
```

**Comment by DannyBen** [comment]
Well... I have two suggestions.

### A. Remove this from the initialize

1. As a user, I do not want any command line to connect to the internet and do version checks as soon as I run it.
2. I would consider having a `yourscript update` command or something similar that checks for updates.
3. As a developer, you already see this is causing problems - initialization is best kept minimal, not only in this context.

### B. Use an environment variable deactivator

1. In your initialize, check for updates only if `$DISABLE_VERSION_CHECK` is unset. (`if [[ -z $DISABLE_VERSION_CHECK ]]; then`)
2. In your `~/.zshrc` call `eval $(DISABLE_VERSION_CHECK=1 yourscript completion)`


Obviously, my strong recommendation is for option A or similar.

**Comment by Linbreux** [comment]
@DannyBen 

Thanks for the information. This will indeed work! 

Nice tool btw :)

**Comment by DannyBen** [comment]
Any time :)
