### ISSUE TITLE
Missing erb dependency?

### ISSUE THREAD

**Issue by pcrockett** [DannyBen/bashly#572]
### Bashly Version

Latest Ruby Gem

### Description

I'm on a relatively barebones install of Archlinux. I have ruby installed:

```plaintext
$ ruby -v
ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [x86_64-linux]
```

I installed bashly via `gem install bashly` as the docs say, and everything looked fine during install. `base-devel` and `libyaml` are also installed on my system. However when I run `bashly --version` I get this:

```plaintext
<internal:/usr/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require': cannot load such file -- erb (LoadError)
Did you mean?  drb
	from <internal:/usr/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from /home/phil/.local/share/gem/ruby/3.3.0/gems/bashly-1.2.6/lib/bashly/extensions/yaml.rb:1:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from <internal:/usr/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from /home/phil/.local/share/gem/ruby/3.3.0/gems/requires-1.1.0/lib/requires.rb:8:in `block in requires'
	from /home/phil/.local/share/gem/ruby/3.3.0/gems/requires-1.1.0/lib/requires.rb:7:in `each'
	from /home/phil/.local/share/gem/ruby/3.3.0/gems/requires-1.1.0/lib/requires.rb:7:in `requires'
	from /home/phil/.local/share/gem/ruby/3.3.0/gems/bashly-1.2.6/lib/bashly.rb:7:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from <internal:/usr/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from /home/phil/.local/share/gem/ruby/3.3.0/gems/bashly-1.2.6/bin/bashly:2:in `<top (required)>'
	from /home/phil/.local/share/gem/ruby/3.3.0/bin/bashly:25:in `load'
	from /home/phil/.local/share/gem/ruby/3.3.0/bin/bashly:25:in `<main>'
```

### Reproduction Steps

Here's a Dockerfile that reproduces it:

```dockerfile
FROM docker.io/library/archlinux@sha256:876f1f601e5fe6ceda682ac9b0a8df06be695fe9e2c85d04f48a877f17e46b45

RUN pacman -Syu --noconfirm ruby base-devel libyaml
ENV PATH="/root/.local/share/gem/ruby/3.3.0/bin:${PATH}"
RUN gem install bashly
RUN bashly --version
```

Just save this file in your current working directory and run `docker build .`.

**Comment by DannyBen** [comment]
Thanks. Checking.

My initial guess is that this is due to the fact that Ruby 3.3.x started gradually removing *bundled* gems, and [gtx](https://github.com/dannyben/gtx) - the template engine used by bashly, [does not install erb](https://github.com/DannyBen/gtx/blob/master/gtx.gemspec).

If I am right, it should be just a matter of releasing an updated gtx version.

**Comment by DannyBen** [comment]
Quick fix is to add `ruby-erb` to your pacman install:

```dockerfile
RUN pacman -Syu --noconfirm ruby base-devel libyaml ruby-erb
```

**Comment by pcrockett** [comment]
Wonderful. Fixed, thanks.

**Comment by pcrockett** [comment]
Interesting: It works fine with Ruby 3.3, however Ruby 3.1 and 3.2 are failing in a similar way but with `yaml.rb`.

This one I'm seeing in GitHub actions: https://github.com/pcrockett/asdf-bashly/actions/runs/11749003112/job/32734310924?pr=12

**Comment by DannyBen** [comment]
I believe this is a different story.
The OS libraries needed for YAML are not installed by bare bones linux setups.

Same problem (even before 3.x) with Alpine linux. See my alpine ruby image:
https://github.com/DannyBen/docker-alpine-ruby/blob/master/Dockerfile

Try adding `libyaml` with pacman.

**Comment by DannyBen** [comment]
Oh - I see now your actions are on ubuntu.
You need `libyaml-dev` as can be seen in bashly's own GitHub Actions tests:

https://github.com/DannyBen/bashly/blob/1e567aa547558b8bd1c62709a287cd7d5c8c003c/.github/workflows/test.yml#L38

**Comment by pcrockett** [comment]
Hm, I don't think it's an OS dependency. Here's the output of the `apt-get` command (on both my GH actions workflow and yours):

```plaintext
Reading package lists...
Building dependency tree...
Reading state information...
libyaml-dev is already the newest version (0.2.2-1build2).
0 upgraded, 0 newly installed, 0 to remove and 28 not upgraded.
```

and it still fails: https://github.com/pcrockett/asdf-bashly/actions/runs/11757332243/job/32754468692?pr=13

Will look around and see if I can figure out what's different between my Actions workflow and yours.

**Comment by DannyBen** [comment]
See the bashly test workflow - it uses ubuntu, and tests with all active Ruby versions.

**Comment by pcrockett** [comment]
nope. subbornly choosing to install bashly inside an isolated environment. `gem install` seems just as bad as `pip install` to me (and yet everyone recommends it...).

anyway, fixed my issue by using bundler to manage my environment. it was unrelated to this issue. looks like everything's good.

for what it's worth, bundler warns me that `fiddle` and `logger` will soon be moved out of the ruby stdlib, and recommends adding those to your Gemfile.

**Comment by DannyBen** [comment]
`logger` is already in - although it is not a direct dependency of bashly, it is required by `filewatcher` (`bashly generate --watch`), and the filewatcher author should add it eventually.

https://github.com/DannyBen/bashly/blob/1e567aa547558b8bd1c62709a287cd7d5c8c003c/bashly.gemspec#L28

`fiddle` is not required by bashly, or any of its dependencies, as far as my `Gemfile.lock` shows.
