### ISSUE TITLE
Feature req: config option to remove the deps() array

### ISSUE THREAD

**Issue by dsmith4-godaddy** [DannyBen/bashly#575]
### Description

One of my colleagues wanted to know why all my script's dependencies were being stored in an array, and in my case, there's no good reason AFAICT. It would be nice to have the option to remove the deps array entirely, and simply do the dependency checks/error out if a dependency is missing.

(This probably shouldn't be the default to avoid breaking backwards compat, but being able to add/uncomment a line in settings.yml would be nice.)

Yes, it's silly, but some of my colleagues are pedantic 🤣 

Thank you for your work on this, by the way, it's saved me several hours of boilerplate-copy-and-pasting this year!

**Comment by DannyBen** [comment]
Yes, this is silly, but also understandable :).

The reason for this was born in https://github.com/DannyBen/bashly/issues/354#issuecomment-1452081178 .

Just creating a setting that disables this particular array does not make a whole lot of sense to me, but perhaps a `disable` setting that accepts an array that disables one or more optional *things* could be useful.

I will think about it some more.

**Comment by DannyBen** [comment]
What is your thought about #576?

**Comment by dsmith4-godaddy** [comment]
When you're using inspect_args, yes, having the deps in an array absolutely makes sense. There probably are other use cases for it too, maybe a program needs to behave _slightly_ differently depending on which specific deps are/aren't available (curl vs wget is the first thing that comes to mind).

I have a couple thoughts about #576 that I'll note there. Thanks again!
