### ISSUE TITLE
Consider allowing capital internal vars (`$ARGS`, `$DEPS`, etc)

### ISSUE THREAD

**Issue by DannyBen** [DannyBen/bashly#586]
### Description

As discussed in #581, perhaps we can:

1. Have a `capital_global_vars` setting
2. When it is true, add a `declare -gn ARGS=args DEPS=deps` to enable both capital and lowercase vars

Another option is to have more flexibility with this kind of settings scheme:

```yaml
args_varname=ARGS
deps_varname=DEPENDENCIES
other_args_varname=EXTRAS
```

**Comment by DannyBen** [comment]
@meleu - this feature is implemented in #587 with a slightly different settings syntax.
I think this works well.

Next - I want to move all the `declare` to from `run()` `initialize()`.

**Comment by DannyBen** [comment]
This is ready to be tested if interested.

**Comment by meleu** [comment]
Yeah, it works beautifully!

**Comment by DannyBen** [comment]
Alright - so we can close this I guess, and I will probably release tomorrow.
