### ISSUE TITLE
support just sourcing of the generated shell file.

### ISSUE THREAD

**Issue by dkebler** [DannyBen/bashly#59]
I do this kind of thing at the end of a file I consider a "module" to source with a primary function but may want to run directly

`(return 0 2>/dev/null) || run "$@"`

that way I can source as a module (say at login) and run it later as function, but if I want to execute right then I can.
This means I namespace any "helper" functions so they will not collide with other sourced functions in my login shell.  Maybe they should be prefaced with the command name.   What would also be required is to change the `run` function to the name of the command being generated.

If that is not wanted during development then maybe bashly generate might have a --pro flag to do this in "production".

**Comment by DannyBen** [comment]
Bashly is designed to generate executable command line scripts, nothing else.

I do not see the point in generating a sourceable command line script, and I definitely don't want to namespace anything - take a look at a [real world bashly-generated script](https://github.com/DannyBen/rush-cli/blob/master/rush), see that it is already long and complex.

I don't see the benefits, but feel free to enlighten me if you think I am wrong.

**Comment by DannyBen** [comment]
@dkebler is there any reason to prefer this:

```bash
(return 0 2>/dev/null) || run "$@"
```

over something like this?

```bash
if [[ ${BASH_SOURCE[0]} == "$0" ]]; then
    main "$@"
fi
```

**Comment by DannyBen** [comment]
Version 0.4.1 is released with an option to wrap the output in a function. Docker image is being built now.
