### ISSUE TITLE
Generate user documentation from bashly.yml

### ISSUE THREAD

**Issue by roquie** [DannyBen/bashly#69]
Hi!

Great tool, we use it for our CI scripts, it helpful to follow DRY principles.

I think `bashly.yml` can be used not only for generate  cli command. Also, it useful for generate Markdown documentation in long format where will be described all command and sub-command.

What think about it?

**Comment by DannyBen** [comment]
Glad you like it.

Can you give me an example of an expected markdown output?

**Comment by roquie** [comment]
Given that `bashly` supports nesting commands, the most convenient format for fully displaying documentation is to display it in a similar way as `homebrew` does in `man` (`man brew`). Example in the attachment. Markdown here will help with lists, titles, and highlighting options/flags/environment variables.

[example.txt](https://github.com/DannyBen/bashly/files/6236352/example.txt)

**Comment by DannyBen** [comment]
It shouldn't be too difficult to implement, the question is - should it be a part of bashly or not.

For the most part, the `--help` flag provides all the documentation you need. In the real world, you only need man pages or READMEs in case there is more information to share that is not available in the `--help` usage text.

If we implement this in bashly, the information will be identical, only formatted differently. 

In addition, if we already generate a markdown documentation, someone else might want to generate man pages, or HTML documentation. So I am a little hesitant to create a "feature creep".

Let me think about it some more, and if you have thoughts on the above, feel free to share.

**Comment by roquie** [comment]
I see two ways.

First: implement this in bashly, because `bashly.yaml` an inseparable part of bashly.

Second: make a plugin system for bashly, but I think for it is a large overhead. May be used a mixed solution: create an `documentation` abstraction in bashly for generate different formats. Anyone can add a HTML/PDF doc format.

**Comment by DannyBen** [comment]
I have already tried several approaches, but ultimately, ended up with a complex structure that is essentially generating the same thing as the usage text (`--help`) using different views.

Generating the script from the YAML today is a process that is done by using many small code snippets (see the [views](https://github.com/DannyBen/bashly/tree/master/lib/bashly) folder). This process needs to take into account many nuances, such as: Do we have subcommands or not? For each command, does it have flags? Default values? Required values? and many more,

**Comment by DannyBen** [comment]
I am closing this for now, the complexity of implementing it does not justify the benefits.

I am still open to be convinced otherwise.

**Comment by DannyBen** [comment]
@roquie if this is still relevant, I have a proposal discussed in #415, in case you wish to chime in.

**Comment by DannyBen** [comment]
Version 1.1.0 is released with this feature. Run `bashly render --help` for more information, or [read the docs](https://bashly.dannyb.co/advanced/rendering/).
