### ISSUE TITLE
heredocs are rendered with prefixed spaces causing the compiled CLI to fail

### ISSUE THREAD

**Issue by abh1kg** [DannyBen/bashly#73]
Heredoc expressions such as the following in command files are rendered with two prefixed spaces for the end character. This causes issues with the heredoc and causes the command to fail. Example:

In `command` file:

```
ext_peer_config=$(
  cat <<EOF
cidr: 10.${ip_segment}.0.0/16
id: ${peer_id}
name: ${peer_name}
EOF
    )
```

In the generated file (after running `bashly generate`):

```
  cat >"$peer_context_file" <<EOL
  cidr: 10.${ip_segment}.0.0/16
  id: ${peer_id}
  name: ${peer_name}
  EOL # there are 2 spaces before this character
```

**Comment by DannyBen** [comment]
Yes, not much that can be done about this. Bashly indents your code and heredoc does not follow proper indentation rules.

There is however a workaround. Functions that are defined in the `lib` folder will be added as is, without indentation. You can create a function in that folder and use heredoc there, or avoid using heredoc altogether.

**Comment by DannyBen** [comment]
I am going to close this, but feel free to comment or open a new issue if you have new thoughts on the subject.

**Comment by DannyBen** [comment]
cc @abh1kg 

Bashly 0.7.10 was released, with improved support for cases where heredoc is needed.

By settings the `BASHLY_TAB_INDENT=1` environment variable (or via the new [settings.yml](https://bashly.dannyb.co/usage/settings/)), the generated script will have all its leading spaces indented as tabs instead, which allows use of this heredoc format:

```bash
cat <<-EOF
multiline
heredoc text
EOF
```

See the [heredoc example](https://github.com/DannyBen/bashly/tree/master/examples/heredoc#readme).

**Comment by DannyBen** [comment]
I have made heredoc work naturally, without the need to do anything (#496). bashly will no longer apply additional indentation to the strings inside a heredoc block.

This is available in the edge version, if anyone wishes to test it.
