### ISSUE TITLE
catch_all arguments are not printed if not any arg is specified

### ISSUE THREAD

**Issue by RonnyLV** [DannyBen/bashly#74]
`catch_all` arguments are not printed if not any arg is specified.

Expected generated help for `catch_all` `label` and `help` even when `args` is not filled in.

**Comment by DannyBen** [comment]
Can you provide the smallest YAML that reproduces the problem?

**Comment by RonnyLV** [comment]
```yaml
name: cli
help: Sample application
version: 0.1.0

commands:
- name: download
  short: d
  help: Download a file
  catch_all:
    label: "URLs"
    help: "List of URLs"
