### ISSUE TITLE
Don't break uninterrupted strings longer than 80 characters

### ISSUE THREAD

**Issue by iamjackg** [DannyBen/bashly#79]
If I have a URL that is longer than 80 characters in a `help` block, it gets split in two. This prevents people from opening it by clicking on it, and makes it annoying to copy it. I think it makes sense to leave long, uninterrupted strings alone and let the terminal deal with it.

Is this as simple as removing this regex substitution? :thinking: https://github.com/DannyBen/bashly/blob/6bb6d2f957d97c4b8045ec0fd64a7d2a71324758/lib/bashly/extensions/string.rb#L19

**Comment by DannyBen** [comment]
Why do you have a long URL in the help message?

**Comment by iamjackg** [comment]
The help message points to a document which defines the data format supported by the tool, which is shared with other software around the company. I can't use a URL shortener, unfortunately, and I don't think the tool's `help` is the right place to explain a data format in detail anyway.

**Comment by DannyBen** [comment]
Well, this `String#wrap` function puts higher emphasis on ensuring that the text is **always** wrapped to the requested length. It is being opinionated with the opinion that you should not have lines longer than 78 characters in any text string.

I am not sure how I feel yet about removing this "opinion", as it is an integral part of ensuring that the scripts generated by bashly are clean, neat, organized and consistent.

**Comment by DannyBen** [comment]
Ok - after self deliberation, I withdraw my objection :)

I have pushed a fix in #80.

Do you want to test it to ensure it works as expected, before I bake a release?

If so, create a Gemfile with this content

```ruby
source "https://rubygems.org"
git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
gem "bashly", github: 'dannyben/bashly', branch: 'fix/string-wrap'
```

Then run `bundle`, and then `bundle exec bashly generate` in your bashly project folder.

**Comment by iamjackg** [comment]
Just tried it, looks perfect! Thank you so much :)

**Comment by DannyBen** [comment]
Version 0.4.5 was released to rubygems.
The docker version is being built now.

**Comment by DannyBen** [comment]
@iamjackg - I have added support for a help `footer` option, which can be used to add a text that will appear at the bottom of the `--help` text. The need for this was inspired by your use case - I feel it is a more appropriate place to say "For more information visit http://..."

Version 0.5.1 was just released with this support, and the docker image will be ready shortly.

If it is of any interest, see the [footer example](/examples/footer#readme).

**Comment by iamjackg** [comment]
Ooo, very cool! I like that. In fact, I almost like it more than using `help` for detailed explanations, because when using `help` the user has to scroll through a potentially long piece of text before they get to what they're interested in: the command flags.

**Comment by DannyBen** [comment]
Yes, I agree the original `help` option is intended more for a one-liner header.

Hopefully the `footer` provides some more flexibility.
