### ISSUE TITLE
Exit gracefully if Bash is too old

### ISSUE THREAD

**Issue by iamjackg** [DannyBen/bashly#90]
Bashly is not compatible with older Bash versions, which is totally fine. I'm wondering if it would make sense to fail with a helpful error message if `$BASH_VERSION` is too old? As it is now, it just causes a syntax error.

I have a lot of users on OSX, which (of course 🙄) ships with a very old version of Bash, and even if I specify in the instructions that a newer version is needed, it still catches people off guard. I'd love to have a way to have the script itself tell the user what they need to do.

I suppose an alternative would be to have a pre-command function that can run at startup for every single command, so people can autonomously implement checks like this, but it would need to run before anything is done that requires a newer Bash version.

What are your thoughts?

**Comment by DannyBen** [comment]
Yes. It might be a good idea to implement.

You can easily add this to your script. Just add it in your `src/initialize.sh`

```bash
if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
  echo "This script requires bash >= 4"
  exit 1
fi
```

**Comment by DannyBen** [comment]
I have implemented it in #91 and will wait a little before merging, in case you have comments.

Once this is merged, it will automatically exit gracefully on older bash versions with the error: 

```
bash version 4 or higher is required
```

which can be overridden if you want, by adding the strings customization yaml:

```
$ bashly add strings
```

and then update `src/bashly-strings.yml`:

```yaml
unsupported_bash_version: "your error string"
```

**Comment by iamjackg** [comment]
This is perfect! I feel like I knew about `src/initialize.sh` but I couldn't find any mention of it in the documentation :thinking: Is it only used in the example scripts?

Either way this is exactly what I needed. Thank you!

**Comment by DannyBen** [comment]
Well - the `initialize.sh` script is generated in to your `src` folder, and it is commented.
I probably assumed people would be curious and read it... :)

I added it to the documentation (not yet public).

Still - once I release the next version, you will not need to implement it yourself, as it will be built in.

**Comment by DannyBen** [comment]
Version 0.6.3 is live, with the graceful exit, and I have added [Initialization function](https://bashly.dannyb.co/usage/writing-your-scripts/#initialization-function) to the docs.

Thanks for the good suggestion.
