### ISSUE TITLE
bashly won't run by default on Mac, due to zsh standard and bash 3.2

### ISSUE THREAD

**Issue by thomasaarholt** [DannyBen/bashly#99]
The autogenerated files by `bashly` check for `bash` version 4 or higher. On MacOS, the default version is version 3.2, because [license reasons](https://itnext.io/upgrading-bash-on-macos-7138bd1066ba). This leads to the message `bash version 4 or higher is required`.

Instead of bash, MacOS defaults to `zsh` (by default version 5.8 on latest macOS), which afaik supports all the relevant functionality in bash 4+. 

I've just done a bit of testing, and there are two solutions:

# Solution #1
`brew install bash` installs the latest bash in the brew directory, then links it to `bash`, and does *not* overwrite default shell (zsh is still default). This all that is required for bashly scripts to run, but updating bash can be viewed as invasive by sysadmin.

# Solution #2
Specifically, the two following parts of generated bash scripts need editing on Mac:

- Line 1: `#!/usr/bin/env bash` -> `#!/usr/bin/env zsh`
- Further down, this needs to be commented out or changed to support zsh:
```
  if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
    printf "bash version 4 or higher is required\n"
    exit 1
  fi
```
I don't know if there's a way to target "default system shell" in the shebang. That would prevent the problem on Mac, but could lead to issues if one is using e.g. `fish` shell and has bash 4+ available.

Personally, I'm sticking with solution 1, but I thought I'd share my thoughts here, since there were no results for a search for `zsh` on the github.

**Comment by DannyBen** [comment]
The generated scripts require bash 4 as stated in the [prerequisites](https://bashly.dannyb.co/installation/#prerequisites) section of the documentation.

Changing the shebang to `zsh` is not a good idea as it will just require double effort in testing, and will force the generated script to use the lowest common demonimator. You can still run bash scripts in zsh (or any other) shell, as long as a modern bash is installed.

Bash 4.0 was released in 2009 - the complaint should be directed to Apple for bundling a 12 year old software.

I can add the instruction for `brew install bash` in the prerequisites section - will that be acceptable as a hint? In addition, if you know your users are mostly on mac with outdated bash, you can customize this error by adding the following file to your `src` folder:

```yaml
# src/bashly-strings.yml
unsupported_bash_version: "bash version 4 or higher is required (brew install bash on mac)"
```

See [Custom Strings](https://bashly.dannyb.co/advanced/strings/) in the docs for more info.

Also, the graceful exit when bash is < 4 was recently added by a user request (#90).

**Comment by thomasaarholt** [comment]
Nice! Thanks for the suggestion on the .yml, we'll do that!
The graceful exist makes total sense :)

I agree with blaming Apple for all this nonsense!

**Comment by DannyBen** [comment]
Cool.

I will update the docs, and if more users land on this issue and think that changing the default error message to include instructions to `brew install bash` is a good idea, please comment here and I will add it if there is demand.

Thanks for your report, and If something else is unclear or not working as expected, feel free to open a new issue.

**Comment by thomasaarholt** [comment]
Happy to help :) sorry if my "solutions" came across as a bit "not-thought-through" - I was just trying to think of ideas.
Very excited to use the bashly script that we've created! :)

**Comment by DannyBen** [comment]
> sorry if my "solutions" came across as a bit "not-thought-through"

Are you kidding? It is very appreciated that you took the time to look for solutions and not just point out a problem.

In fact, I feel like I should be the one to apologize for not having this requirement (and solution) more clearly on the documentation site - so let's meet in the middle, and nobody apologizes to nobody! :)

> Very excited to use the bashly script that we've created! :)

Happy to hear! 
There are quite a few "hidden features" that can be found in the documentations and examples, and also note that the generated script is by design, very human readable.

**Comment by thomasaarholt** [comment]
Sounds great 😄 Thanks for your help!

**Comment by DannyBen** [comment]
Oh - and one last tip:

If you are serious about your bash scripts, and the quality of your code, you should use [shellcheck](https://github.com/koalaman/shellcheck#readme) to verify the output.

All code generated by bashly itself, is shellcheck compliant.

**Comment by thomasaarholt** [comment]
Ooh, that's an exciting package that I was totally unaware of! Thanks!
